
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  ADMIN: 'ADMIN',
  USER: 'USER'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const DocumentType = {
  NOTE: 'NOTE',
  DOCUMENT: 'DOCUMENT',
  DRAWING: 'DRAWING',
  DESIGN: 'DESIGN',
  STICKY_NOTES: 'STICKY_NOTES',
  MIND_MAP: 'MIND_MAP',
  RAG: 'RAG',
  RESEARCH_PAPER: 'RESEARCH_PAPER',
  FLIPBOOK: 'FLIPBOOK',
  PRESENTATION: 'PRESENTATION'
} as const

export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType]


export const PresentationStatus = {
  DRAFT: 'DRAFT',
  OUTLINE: 'OUTLINE',
  CONTENT: 'CONTENT',
  FAILED: 'FAILED'
} as const

export type PresentationStatus = (typeof PresentationStatus)[keyof typeof PresentationStatus]


export const PresentationThemeType = {
  SYSTEM: 'SYSTEM',
  CUSTOM: 'CUSTOM'
} as const

export type PresentationThemeType = (typeof PresentationThemeType)[keyof typeof PresentationThemeType]


export const ImageLibraryType = {
  UPLOADED: 'UPLOADED',
  AI: 'AI'
} as const

export type ImageLibraryType = (typeof ImageLibraryType)[keyof typeof ImageLibraryType]
