
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BaseDocument` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model BaseDocument
 * 
 */
export type BaseDocumentModel = runtime.Types.Result.DefaultSelection<Prisma.$BaseDocumentPayload>

export type AggregateBaseDocument = {
  _count: BaseDocumentCountAggregateOutputType | null
  _min: BaseDocumentMinAggregateOutputType | null
  _max: BaseDocumentMaxAggregateOutputType | null
}

export type BaseDocumentMinAggregateOutputType = {
  id: string | null
  title: string | null
  type: $Enums.DocumentType | null
  isPublic: boolean | null
  thumbnailUrl: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BaseDocumentMaxAggregateOutputType = {
  id: string | null
  title: string | null
  type: $Enums.DocumentType | null
  isPublic: boolean | null
  thumbnailUrl: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BaseDocumentCountAggregateOutputType = {
  id: number
  title: number
  type: number
  isPublic: number
  thumbnailUrl: number
  userId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type BaseDocumentMinAggregateInputType = {
  id?: true
  title?: true
  type?: true
  isPublic?: true
  thumbnailUrl?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type BaseDocumentMaxAggregateInputType = {
  id?: true
  title?: true
  type?: true
  isPublic?: true
  thumbnailUrl?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type BaseDocumentCountAggregateInputType = {
  id?: true
  title?: true
  type?: true
  isPublic?: true
  thumbnailUrl?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type BaseDocumentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BaseDocument to aggregate.
   */
  where?: Prisma.BaseDocumentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BaseDocuments to fetch.
   */
  orderBy?: Prisma.BaseDocumentOrderByWithRelationInput | Prisma.BaseDocumentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BaseDocumentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BaseDocuments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BaseDocuments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BaseDocuments
  **/
  _count?: true | BaseDocumentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BaseDocumentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BaseDocumentMaxAggregateInputType
}

export type GetBaseDocumentAggregateType<T extends BaseDocumentAggregateArgs> = {
      [P in keyof T & keyof AggregateBaseDocument]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBaseDocument[P]>
    : Prisma.GetScalarType<T[P], AggregateBaseDocument[P]>
}




export type BaseDocumentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BaseDocumentWhereInput
  orderBy?: Prisma.BaseDocumentOrderByWithAggregationInput | Prisma.BaseDocumentOrderByWithAggregationInput[]
  by: Prisma.BaseDocumentScalarFieldEnum[] | Prisma.BaseDocumentScalarFieldEnum
  having?: Prisma.BaseDocumentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BaseDocumentCountAggregateInputType | true
  _min?: BaseDocumentMinAggregateInputType
  _max?: BaseDocumentMaxAggregateInputType
}

export type BaseDocumentGroupByOutputType = {
  id: string
  title: string
  type: $Enums.DocumentType
  isPublic: boolean
  thumbnailUrl: string | null
  userId: string
  createdAt: Date
  updatedAt: Date
  _count: BaseDocumentCountAggregateOutputType | null
  _min: BaseDocumentMinAggregateOutputType | null
  _max: BaseDocumentMaxAggregateOutputType | null
}

type GetBaseDocumentGroupByPayload<T extends BaseDocumentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BaseDocumentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BaseDocumentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BaseDocumentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BaseDocumentGroupByOutputType[P]>
      }
    >
  >



export type BaseDocumentWhereInput = {
  AND?: Prisma.BaseDocumentWhereInput | Prisma.BaseDocumentWhereInput[]
  OR?: Prisma.BaseDocumentWhereInput[]
  NOT?: Prisma.BaseDocumentWhereInput | Prisma.BaseDocumentWhereInput[]
  id?: Prisma.StringFilter<"BaseDocument"> | string
  title?: Prisma.StringFilter<"BaseDocument"> | string
  type?: Prisma.EnumDocumentTypeFilter<"BaseDocument"> | $Enums.DocumentType
  isPublic?: Prisma.BoolFilter<"BaseDocument"> | boolean
  thumbnailUrl?: Prisma.StringNullableFilter<"BaseDocument"> | string | null
  userId?: Prisma.StringFilter<"BaseDocument"> | string
  createdAt?: Prisma.DateTimeFilter<"BaseDocument"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BaseDocument"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  favorites?: Prisma.FavoriteDocumentListRelationFilter
  presentation?: Prisma.XOR<Prisma.PresentationNullableScalarRelationFilter, Prisma.PresentationWhereInput> | null
}

export type BaseDocumentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  favorites?: Prisma.FavoriteDocumentOrderByRelationAggregateInput
  presentation?: Prisma.PresentationOrderByWithRelationInput
}

export type BaseDocumentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BaseDocumentWhereInput | Prisma.BaseDocumentWhereInput[]
  OR?: Prisma.BaseDocumentWhereInput[]
  NOT?: Prisma.BaseDocumentWhereInput | Prisma.BaseDocumentWhereInput[]
  title?: Prisma.StringFilter<"BaseDocument"> | string
  type?: Prisma.EnumDocumentTypeFilter<"BaseDocument"> | $Enums.DocumentType
  isPublic?: Prisma.BoolFilter<"BaseDocument"> | boolean
  thumbnailUrl?: Prisma.StringNullableFilter<"BaseDocument"> | string | null
  userId?: Prisma.StringFilter<"BaseDocument"> | string
  createdAt?: Prisma.DateTimeFilter<"BaseDocument"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BaseDocument"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  favorites?: Prisma.FavoriteDocumentListRelationFilter
  presentation?: Prisma.XOR<Prisma.PresentationNullableScalarRelationFilter, Prisma.PresentationWhereInput> | null
}, "id">

export type BaseDocumentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.BaseDocumentCountOrderByAggregateInput
  _max?: Prisma.BaseDocumentMaxOrderByAggregateInput
  _min?: Prisma.BaseDocumentMinOrderByAggregateInput
}

export type BaseDocumentScalarWhereWithAggregatesInput = {
  AND?: Prisma.BaseDocumentScalarWhereWithAggregatesInput | Prisma.BaseDocumentScalarWhereWithAggregatesInput[]
  OR?: Prisma.BaseDocumentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BaseDocumentScalarWhereWithAggregatesInput | Prisma.BaseDocumentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BaseDocument"> | string
  title?: Prisma.StringWithAggregatesFilter<"BaseDocument"> | string
  type?: Prisma.EnumDocumentTypeWithAggregatesFilter<"BaseDocument"> | $Enums.DocumentType
  isPublic?: Prisma.BoolWithAggregatesFilter<"BaseDocument"> | boolean
  thumbnailUrl?: Prisma.StringNullableWithAggregatesFilter<"BaseDocument"> | string | null
  userId?: Prisma.StringWithAggregatesFilter<"BaseDocument"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BaseDocument"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BaseDocument"> | Date | string
}

export type BaseDocumentCreateInput = {
  id?: string
  title: string
  type: $Enums.DocumentType
  isPublic?: boolean
  thumbnailUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutDocumentsInput
  favorites?: Prisma.FavoriteDocumentCreateNestedManyWithoutDocumentInput
  presentation?: Prisma.PresentationCreateNestedOneWithoutBaseInput
}

export type BaseDocumentUncheckedCreateInput = {
  id?: string
  title: string
  type: $Enums.DocumentType
  isPublic?: boolean
  thumbnailUrl?: string | null
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  favorites?: Prisma.FavoriteDocumentUncheckedCreateNestedManyWithoutDocumentInput
  presentation?: Prisma.PresentationUncheckedCreateNestedOneWithoutBaseInput
}

export type BaseDocumentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutDocumentsNestedInput
  favorites?: Prisma.FavoriteDocumentUpdateManyWithoutDocumentNestedInput
  presentation?: Prisma.PresentationUpdateOneWithoutBaseNestedInput
}

export type BaseDocumentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  favorites?: Prisma.FavoriteDocumentUncheckedUpdateManyWithoutDocumentNestedInput
  presentation?: Prisma.PresentationUncheckedUpdateOneWithoutBaseNestedInput
}

export type BaseDocumentCreateManyInput = {
  id?: string
  title: string
  type: $Enums.DocumentType
  isPublic?: boolean
  thumbnailUrl?: string | null
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BaseDocumentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BaseDocumentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BaseDocumentListRelationFilter = {
  every?: Prisma.BaseDocumentWhereInput
  some?: Prisma.BaseDocumentWhereInput
  none?: Prisma.BaseDocumentWhereInput
}

export type BaseDocumentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BaseDocumentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BaseDocumentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BaseDocumentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BaseDocumentScalarRelationFilter = {
  is?: Prisma.BaseDocumentWhereInput
  isNot?: Prisma.BaseDocumentWhereInput
}

export type BaseDocumentCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BaseDocumentCreateWithoutUserInput, Prisma.BaseDocumentUncheckedCreateWithoutUserInput> | Prisma.BaseDocumentCreateWithoutUserInput[] | Prisma.BaseDocumentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BaseDocumentCreateOrConnectWithoutUserInput | Prisma.BaseDocumentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BaseDocumentCreateManyUserInputEnvelope
  connect?: Prisma.BaseDocumentWhereUniqueInput | Prisma.BaseDocumentWhereUniqueInput[]
}

export type BaseDocumentUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BaseDocumentCreateWithoutUserInput, Prisma.BaseDocumentUncheckedCreateWithoutUserInput> | Prisma.BaseDocumentCreateWithoutUserInput[] | Prisma.BaseDocumentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BaseDocumentCreateOrConnectWithoutUserInput | Prisma.BaseDocumentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BaseDocumentCreateManyUserInputEnvelope
  connect?: Prisma.BaseDocumentWhereUniqueInput | Prisma.BaseDocumentWhereUniqueInput[]
}

export type BaseDocumentUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BaseDocumentCreateWithoutUserInput, Prisma.BaseDocumentUncheckedCreateWithoutUserInput> | Prisma.BaseDocumentCreateWithoutUserInput[] | Prisma.BaseDocumentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BaseDocumentCreateOrConnectWithoutUserInput | Prisma.BaseDocumentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BaseDocumentUpsertWithWhereUniqueWithoutUserInput | Prisma.BaseDocumentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BaseDocumentCreateManyUserInputEnvelope
  set?: Prisma.BaseDocumentWhereUniqueInput | Prisma.BaseDocumentWhereUniqueInput[]
  disconnect?: Prisma.BaseDocumentWhereUniqueInput | Prisma.BaseDocumentWhereUniqueInput[]
  delete?: Prisma.BaseDocumentWhereUniqueInput | Prisma.BaseDocumentWhereUniqueInput[]
  connect?: Prisma.BaseDocumentWhereUniqueInput | Prisma.BaseDocumentWhereUniqueInput[]
  update?: Prisma.BaseDocumentUpdateWithWhereUniqueWithoutUserInput | Prisma.BaseDocumentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BaseDocumentUpdateManyWithWhereWithoutUserInput | Prisma.BaseDocumentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BaseDocumentScalarWhereInput | Prisma.BaseDocumentScalarWhereInput[]
}

export type BaseDocumentUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BaseDocumentCreateWithoutUserInput, Prisma.BaseDocumentUncheckedCreateWithoutUserInput> | Prisma.BaseDocumentCreateWithoutUserInput[] | Prisma.BaseDocumentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BaseDocumentCreateOrConnectWithoutUserInput | Prisma.BaseDocumentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BaseDocumentUpsertWithWhereUniqueWithoutUserInput | Prisma.BaseDocumentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BaseDocumentCreateManyUserInputEnvelope
  set?: Prisma.BaseDocumentWhereUniqueInput | Prisma.BaseDocumentWhereUniqueInput[]
  disconnect?: Prisma.BaseDocumentWhereUniqueInput | Prisma.BaseDocumentWhereUniqueInput[]
  delete?: Prisma.BaseDocumentWhereUniqueInput | Prisma.BaseDocumentWhereUniqueInput[]
  connect?: Prisma.BaseDocumentWhereUniqueInput | Prisma.BaseDocumentWhereUniqueInput[]
  update?: Prisma.BaseDocumentUpdateWithWhereUniqueWithoutUserInput | Prisma.BaseDocumentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BaseDocumentUpdateManyWithWhereWithoutUserInput | Prisma.BaseDocumentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BaseDocumentScalarWhereInput | Prisma.BaseDocumentScalarWhereInput[]
}

export type EnumDocumentTypeFieldUpdateOperationsInput = {
  set?: $Enums.DocumentType
}

export type BaseDocumentCreateNestedOneWithoutPresentationInput = {
  create?: Prisma.XOR<Prisma.BaseDocumentCreateWithoutPresentationInput, Prisma.BaseDocumentUncheckedCreateWithoutPresentationInput>
  connectOrCreate?: Prisma.BaseDocumentCreateOrConnectWithoutPresentationInput
  connect?: Prisma.BaseDocumentWhereUniqueInput
}

export type BaseDocumentUpdateOneRequiredWithoutPresentationNestedInput = {
  create?: Prisma.XOR<Prisma.BaseDocumentCreateWithoutPresentationInput, Prisma.BaseDocumentUncheckedCreateWithoutPresentationInput>
  connectOrCreate?: Prisma.BaseDocumentCreateOrConnectWithoutPresentationInput
  upsert?: Prisma.BaseDocumentUpsertWithoutPresentationInput
  connect?: Prisma.BaseDocumentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BaseDocumentUpdateToOneWithWhereWithoutPresentationInput, Prisma.BaseDocumentUpdateWithoutPresentationInput>, Prisma.BaseDocumentUncheckedUpdateWithoutPresentationInput>
}

export type BaseDocumentCreateNestedOneWithoutFavoritesInput = {
  create?: Prisma.XOR<Prisma.BaseDocumentCreateWithoutFavoritesInput, Prisma.BaseDocumentUncheckedCreateWithoutFavoritesInput>
  connectOrCreate?: Prisma.BaseDocumentCreateOrConnectWithoutFavoritesInput
  connect?: Prisma.BaseDocumentWhereUniqueInput
}

export type BaseDocumentUpdateOneRequiredWithoutFavoritesNestedInput = {
  create?: Prisma.XOR<Prisma.BaseDocumentCreateWithoutFavoritesInput, Prisma.BaseDocumentUncheckedCreateWithoutFavoritesInput>
  connectOrCreate?: Prisma.BaseDocumentCreateOrConnectWithoutFavoritesInput
  upsert?: Prisma.BaseDocumentUpsertWithoutFavoritesInput
  connect?: Prisma.BaseDocumentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BaseDocumentUpdateToOneWithWhereWithoutFavoritesInput, Prisma.BaseDocumentUpdateWithoutFavoritesInput>, Prisma.BaseDocumentUncheckedUpdateWithoutFavoritesInput>
}

export type BaseDocumentCreateWithoutUserInput = {
  id?: string
  title: string
  type: $Enums.DocumentType
  isPublic?: boolean
  thumbnailUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  favorites?: Prisma.FavoriteDocumentCreateNestedManyWithoutDocumentInput
  presentation?: Prisma.PresentationCreateNestedOneWithoutBaseInput
}

export type BaseDocumentUncheckedCreateWithoutUserInput = {
  id?: string
  title: string
  type: $Enums.DocumentType
  isPublic?: boolean
  thumbnailUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  favorites?: Prisma.FavoriteDocumentUncheckedCreateNestedManyWithoutDocumentInput
  presentation?: Prisma.PresentationUncheckedCreateNestedOneWithoutBaseInput
}

export type BaseDocumentCreateOrConnectWithoutUserInput = {
  where: Prisma.BaseDocumentWhereUniqueInput
  create: Prisma.XOR<Prisma.BaseDocumentCreateWithoutUserInput, Prisma.BaseDocumentUncheckedCreateWithoutUserInput>
}

export type BaseDocumentCreateManyUserInputEnvelope = {
  data: Prisma.BaseDocumentCreateManyUserInput | Prisma.BaseDocumentCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type BaseDocumentUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.BaseDocumentWhereUniqueInput
  update: Prisma.XOR<Prisma.BaseDocumentUpdateWithoutUserInput, Prisma.BaseDocumentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.BaseDocumentCreateWithoutUserInput, Prisma.BaseDocumentUncheckedCreateWithoutUserInput>
}

export type BaseDocumentUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.BaseDocumentWhereUniqueInput
  data: Prisma.XOR<Prisma.BaseDocumentUpdateWithoutUserInput, Prisma.BaseDocumentUncheckedUpdateWithoutUserInput>
}

export type BaseDocumentUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.BaseDocumentScalarWhereInput
  data: Prisma.XOR<Prisma.BaseDocumentUpdateManyMutationInput, Prisma.BaseDocumentUncheckedUpdateManyWithoutUserInput>
}

export type BaseDocumentScalarWhereInput = {
  AND?: Prisma.BaseDocumentScalarWhereInput | Prisma.BaseDocumentScalarWhereInput[]
  OR?: Prisma.BaseDocumentScalarWhereInput[]
  NOT?: Prisma.BaseDocumentScalarWhereInput | Prisma.BaseDocumentScalarWhereInput[]
  id?: Prisma.StringFilter<"BaseDocument"> | string
  title?: Prisma.StringFilter<"BaseDocument"> | string
  type?: Prisma.EnumDocumentTypeFilter<"BaseDocument"> | $Enums.DocumentType
  isPublic?: Prisma.BoolFilter<"BaseDocument"> | boolean
  thumbnailUrl?: Prisma.StringNullableFilter<"BaseDocument"> | string | null
  userId?: Prisma.StringFilter<"BaseDocument"> | string
  createdAt?: Prisma.DateTimeFilter<"BaseDocument"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BaseDocument"> | Date | string
}

export type BaseDocumentCreateWithoutPresentationInput = {
  id?: string
  title: string
  type: $Enums.DocumentType
  isPublic?: boolean
  thumbnailUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutDocumentsInput
  favorites?: Prisma.FavoriteDocumentCreateNestedManyWithoutDocumentInput
}

export type BaseDocumentUncheckedCreateWithoutPresentationInput = {
  id?: string
  title: string
  type: $Enums.DocumentType
  isPublic?: boolean
  thumbnailUrl?: string | null
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  favorites?: Prisma.FavoriteDocumentUncheckedCreateNestedManyWithoutDocumentInput
}

export type BaseDocumentCreateOrConnectWithoutPresentationInput = {
  where: Prisma.BaseDocumentWhereUniqueInput
  create: Prisma.XOR<Prisma.BaseDocumentCreateWithoutPresentationInput, Prisma.BaseDocumentUncheckedCreateWithoutPresentationInput>
}

export type BaseDocumentUpsertWithoutPresentationInput = {
  update: Prisma.XOR<Prisma.BaseDocumentUpdateWithoutPresentationInput, Prisma.BaseDocumentUncheckedUpdateWithoutPresentationInput>
  create: Prisma.XOR<Prisma.BaseDocumentCreateWithoutPresentationInput, Prisma.BaseDocumentUncheckedCreateWithoutPresentationInput>
  where?: Prisma.BaseDocumentWhereInput
}

export type BaseDocumentUpdateToOneWithWhereWithoutPresentationInput = {
  where?: Prisma.BaseDocumentWhereInput
  data: Prisma.XOR<Prisma.BaseDocumentUpdateWithoutPresentationInput, Prisma.BaseDocumentUncheckedUpdateWithoutPresentationInput>
}

export type BaseDocumentUpdateWithoutPresentationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutDocumentsNestedInput
  favorites?: Prisma.FavoriteDocumentUpdateManyWithoutDocumentNestedInput
}

export type BaseDocumentUncheckedUpdateWithoutPresentationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  favorites?: Prisma.FavoriteDocumentUncheckedUpdateManyWithoutDocumentNestedInput
}

export type BaseDocumentCreateWithoutFavoritesInput = {
  id?: string
  title: string
  type: $Enums.DocumentType
  isPublic?: boolean
  thumbnailUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutDocumentsInput
  presentation?: Prisma.PresentationCreateNestedOneWithoutBaseInput
}

export type BaseDocumentUncheckedCreateWithoutFavoritesInput = {
  id?: string
  title: string
  type: $Enums.DocumentType
  isPublic?: boolean
  thumbnailUrl?: string | null
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  presentation?: Prisma.PresentationUncheckedCreateNestedOneWithoutBaseInput
}

export type BaseDocumentCreateOrConnectWithoutFavoritesInput = {
  where: Prisma.BaseDocumentWhereUniqueInput
  create: Prisma.XOR<Prisma.BaseDocumentCreateWithoutFavoritesInput, Prisma.BaseDocumentUncheckedCreateWithoutFavoritesInput>
}

export type BaseDocumentUpsertWithoutFavoritesInput = {
  update: Prisma.XOR<Prisma.BaseDocumentUpdateWithoutFavoritesInput, Prisma.BaseDocumentUncheckedUpdateWithoutFavoritesInput>
  create: Prisma.XOR<Prisma.BaseDocumentCreateWithoutFavoritesInput, Prisma.BaseDocumentUncheckedCreateWithoutFavoritesInput>
  where?: Prisma.BaseDocumentWhereInput
}

export type BaseDocumentUpdateToOneWithWhereWithoutFavoritesInput = {
  where?: Prisma.BaseDocumentWhereInput
  data: Prisma.XOR<Prisma.BaseDocumentUpdateWithoutFavoritesInput, Prisma.BaseDocumentUncheckedUpdateWithoutFavoritesInput>
}

export type BaseDocumentUpdateWithoutFavoritesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutDocumentsNestedInput
  presentation?: Prisma.PresentationUpdateOneWithoutBaseNestedInput
}

export type BaseDocumentUncheckedUpdateWithoutFavoritesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  presentation?: Prisma.PresentationUncheckedUpdateOneWithoutBaseNestedInput
}

export type BaseDocumentCreateManyUserInput = {
  id?: string
  title: string
  type: $Enums.DocumentType
  isPublic?: boolean
  thumbnailUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BaseDocumentUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  favorites?: Prisma.FavoriteDocumentUpdateManyWithoutDocumentNestedInput
  presentation?: Prisma.PresentationUpdateOneWithoutBaseNestedInput
}

export type BaseDocumentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  favorites?: Prisma.FavoriteDocumentUncheckedUpdateManyWithoutDocumentNestedInput
  presentation?: Prisma.PresentationUncheckedUpdateOneWithoutBaseNestedInput
}

export type BaseDocumentUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type BaseDocumentCountOutputType
 */

export type BaseDocumentCountOutputType = {
  favorites: number
}

export type BaseDocumentCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  favorites?: boolean | BaseDocumentCountOutputTypeCountFavoritesArgs
}

/**
 * BaseDocumentCountOutputType without action
 */
export type BaseDocumentCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BaseDocumentCountOutputType
   */
  select?: Prisma.BaseDocumentCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BaseDocumentCountOutputType without action
 */
export type BaseDocumentCountOutputTypeCountFavoritesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FavoriteDocumentWhereInput
}


export type BaseDocumentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  type?: boolean
  isPublic?: boolean
  thumbnailUrl?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  favorites?: boolean | Prisma.BaseDocument$favoritesArgs<ExtArgs>
  presentation?: boolean | Prisma.BaseDocument$presentationArgs<ExtArgs>
  _count?: boolean | Prisma.BaseDocumentCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["baseDocument"]>

export type BaseDocumentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  type?: boolean
  isPublic?: boolean
  thumbnailUrl?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["baseDocument"]>

export type BaseDocumentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  type?: boolean
  isPublic?: boolean
  thumbnailUrl?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["baseDocument"]>

export type BaseDocumentSelectScalar = {
  id?: boolean
  title?: boolean
  type?: boolean
  isPublic?: boolean
  thumbnailUrl?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type BaseDocumentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "type" | "isPublic" | "thumbnailUrl" | "userId" | "createdAt" | "updatedAt", ExtArgs["result"]["baseDocument"]>
export type BaseDocumentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  favorites?: boolean | Prisma.BaseDocument$favoritesArgs<ExtArgs>
  presentation?: boolean | Prisma.BaseDocument$presentationArgs<ExtArgs>
  _count?: boolean | Prisma.BaseDocumentCountOutputTypeDefaultArgs<ExtArgs>
}
export type BaseDocumentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BaseDocumentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $BaseDocumentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BaseDocument"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    favorites: Prisma.$FavoriteDocumentPayload<ExtArgs>[]
    presentation: Prisma.$PresentationPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    type: $Enums.DocumentType
    isPublic: boolean
    thumbnailUrl: string | null
    userId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["baseDocument"]>
  composites: {}
}

export type BaseDocumentGetPayload<S extends boolean | null | undefined | BaseDocumentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BaseDocumentPayload, S>

export type BaseDocumentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BaseDocumentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BaseDocumentCountAggregateInputType | true
  }

export interface BaseDocumentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BaseDocument'], meta: { name: 'BaseDocument' } }
  /**
   * Find zero or one BaseDocument that matches the filter.
   * @param {BaseDocumentFindUniqueArgs} args - Arguments to find a BaseDocument
   * @example
   * // Get one BaseDocument
   * const baseDocument = await prisma.baseDocument.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BaseDocumentFindUniqueArgs>(args: Prisma.SelectSubset<T, BaseDocumentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BaseDocumentClient<runtime.Types.Result.GetResult<Prisma.$BaseDocumentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BaseDocument that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BaseDocumentFindUniqueOrThrowArgs} args - Arguments to find a BaseDocument
   * @example
   * // Get one BaseDocument
   * const baseDocument = await prisma.baseDocument.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BaseDocumentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BaseDocumentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BaseDocumentClient<runtime.Types.Result.GetResult<Prisma.$BaseDocumentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BaseDocument that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BaseDocumentFindFirstArgs} args - Arguments to find a BaseDocument
   * @example
   * // Get one BaseDocument
   * const baseDocument = await prisma.baseDocument.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BaseDocumentFindFirstArgs>(args?: Prisma.SelectSubset<T, BaseDocumentFindFirstArgs<ExtArgs>>): Prisma.Prisma__BaseDocumentClient<runtime.Types.Result.GetResult<Prisma.$BaseDocumentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BaseDocument that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BaseDocumentFindFirstOrThrowArgs} args - Arguments to find a BaseDocument
   * @example
   * // Get one BaseDocument
   * const baseDocument = await prisma.baseDocument.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BaseDocumentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BaseDocumentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BaseDocumentClient<runtime.Types.Result.GetResult<Prisma.$BaseDocumentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BaseDocuments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BaseDocumentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BaseDocuments
   * const baseDocuments = await prisma.baseDocument.findMany()
   * 
   * // Get first 10 BaseDocuments
   * const baseDocuments = await prisma.baseDocument.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const baseDocumentWithIdOnly = await prisma.baseDocument.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BaseDocumentFindManyArgs>(args?: Prisma.SelectSubset<T, BaseDocumentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BaseDocumentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BaseDocument.
   * @param {BaseDocumentCreateArgs} args - Arguments to create a BaseDocument.
   * @example
   * // Create one BaseDocument
   * const BaseDocument = await prisma.baseDocument.create({
   *   data: {
   *     // ... data to create a BaseDocument
   *   }
   * })
   * 
   */
  create<T extends BaseDocumentCreateArgs>(args: Prisma.SelectSubset<T, BaseDocumentCreateArgs<ExtArgs>>): Prisma.Prisma__BaseDocumentClient<runtime.Types.Result.GetResult<Prisma.$BaseDocumentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BaseDocuments.
   * @param {BaseDocumentCreateManyArgs} args - Arguments to create many BaseDocuments.
   * @example
   * // Create many BaseDocuments
   * const baseDocument = await prisma.baseDocument.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BaseDocumentCreateManyArgs>(args?: Prisma.SelectSubset<T, BaseDocumentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BaseDocuments and returns the data saved in the database.
   * @param {BaseDocumentCreateManyAndReturnArgs} args - Arguments to create many BaseDocuments.
   * @example
   * // Create many BaseDocuments
   * const baseDocument = await prisma.baseDocument.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BaseDocuments and only return the `id`
   * const baseDocumentWithIdOnly = await prisma.baseDocument.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BaseDocumentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BaseDocumentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BaseDocumentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BaseDocument.
   * @param {BaseDocumentDeleteArgs} args - Arguments to delete one BaseDocument.
   * @example
   * // Delete one BaseDocument
   * const BaseDocument = await prisma.baseDocument.delete({
   *   where: {
   *     // ... filter to delete one BaseDocument
   *   }
   * })
   * 
   */
  delete<T extends BaseDocumentDeleteArgs>(args: Prisma.SelectSubset<T, BaseDocumentDeleteArgs<ExtArgs>>): Prisma.Prisma__BaseDocumentClient<runtime.Types.Result.GetResult<Prisma.$BaseDocumentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BaseDocument.
   * @param {BaseDocumentUpdateArgs} args - Arguments to update one BaseDocument.
   * @example
   * // Update one BaseDocument
   * const baseDocument = await prisma.baseDocument.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BaseDocumentUpdateArgs>(args: Prisma.SelectSubset<T, BaseDocumentUpdateArgs<ExtArgs>>): Prisma.Prisma__BaseDocumentClient<runtime.Types.Result.GetResult<Prisma.$BaseDocumentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BaseDocuments.
   * @param {BaseDocumentDeleteManyArgs} args - Arguments to filter BaseDocuments to delete.
   * @example
   * // Delete a few BaseDocuments
   * const { count } = await prisma.baseDocument.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BaseDocumentDeleteManyArgs>(args?: Prisma.SelectSubset<T, BaseDocumentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BaseDocuments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BaseDocumentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BaseDocuments
   * const baseDocument = await prisma.baseDocument.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BaseDocumentUpdateManyArgs>(args: Prisma.SelectSubset<T, BaseDocumentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BaseDocuments and returns the data updated in the database.
   * @param {BaseDocumentUpdateManyAndReturnArgs} args - Arguments to update many BaseDocuments.
   * @example
   * // Update many BaseDocuments
   * const baseDocument = await prisma.baseDocument.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BaseDocuments and only return the `id`
   * const baseDocumentWithIdOnly = await prisma.baseDocument.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BaseDocumentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BaseDocumentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BaseDocumentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BaseDocument.
   * @param {BaseDocumentUpsertArgs} args - Arguments to update or create a BaseDocument.
   * @example
   * // Update or create a BaseDocument
   * const baseDocument = await prisma.baseDocument.upsert({
   *   create: {
   *     // ... data to create a BaseDocument
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BaseDocument we want to update
   *   }
   * })
   */
  upsert<T extends BaseDocumentUpsertArgs>(args: Prisma.SelectSubset<T, BaseDocumentUpsertArgs<ExtArgs>>): Prisma.Prisma__BaseDocumentClient<runtime.Types.Result.GetResult<Prisma.$BaseDocumentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BaseDocuments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BaseDocumentCountArgs} args - Arguments to filter BaseDocuments to count.
   * @example
   * // Count the number of BaseDocuments
   * const count = await prisma.baseDocument.count({
   *   where: {
   *     // ... the filter for the BaseDocuments we want to count
   *   }
   * })
  **/
  count<T extends BaseDocumentCountArgs>(
    args?: Prisma.Subset<T, BaseDocumentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BaseDocumentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BaseDocument.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BaseDocumentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BaseDocumentAggregateArgs>(args: Prisma.Subset<T, BaseDocumentAggregateArgs>): Prisma.PrismaPromise<GetBaseDocumentAggregateType<T>>

  /**
   * Group by BaseDocument.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BaseDocumentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BaseDocumentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BaseDocumentGroupByArgs['orderBy'] }
      : { orderBy?: BaseDocumentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BaseDocumentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBaseDocumentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BaseDocument model
 */
readonly fields: BaseDocumentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BaseDocument.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BaseDocumentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  favorites<T extends Prisma.BaseDocument$favoritesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BaseDocument$favoritesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FavoriteDocumentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  presentation<T extends Prisma.BaseDocument$presentationArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BaseDocument$presentationArgs<ExtArgs>>): Prisma.Prisma__PresentationClient<runtime.Types.Result.GetResult<Prisma.$PresentationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BaseDocument model
 */
export interface BaseDocumentFieldRefs {
  readonly id: Prisma.FieldRef<"BaseDocument", 'String'>
  readonly title: Prisma.FieldRef<"BaseDocument", 'String'>
  readonly type: Prisma.FieldRef<"BaseDocument", 'DocumentType'>
  readonly isPublic: Prisma.FieldRef<"BaseDocument", 'Boolean'>
  readonly thumbnailUrl: Prisma.FieldRef<"BaseDocument", 'String'>
  readonly userId: Prisma.FieldRef<"BaseDocument", 'String'>
  readonly createdAt: Prisma.FieldRef<"BaseDocument", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BaseDocument", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BaseDocument findUnique
 */
export type BaseDocumentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BaseDocument
   */
  select?: Prisma.BaseDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BaseDocument
   */
  omit?: Prisma.BaseDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BaseDocumentInclude<ExtArgs> | null
  /**
   * Filter, which BaseDocument to fetch.
   */
  where: Prisma.BaseDocumentWhereUniqueInput
}

/**
 * BaseDocument findUniqueOrThrow
 */
export type BaseDocumentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BaseDocument
   */
  select?: Prisma.BaseDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BaseDocument
   */
  omit?: Prisma.BaseDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BaseDocumentInclude<ExtArgs> | null
  /**
   * Filter, which BaseDocument to fetch.
   */
  where: Prisma.BaseDocumentWhereUniqueInput
}

/**
 * BaseDocument findFirst
 */
export type BaseDocumentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BaseDocument
   */
  select?: Prisma.BaseDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BaseDocument
   */
  omit?: Prisma.BaseDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BaseDocumentInclude<ExtArgs> | null
  /**
   * Filter, which BaseDocument to fetch.
   */
  where?: Prisma.BaseDocumentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BaseDocuments to fetch.
   */
  orderBy?: Prisma.BaseDocumentOrderByWithRelationInput | Prisma.BaseDocumentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BaseDocuments.
   */
  cursor?: Prisma.BaseDocumentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BaseDocuments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BaseDocuments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BaseDocuments.
   */
  distinct?: Prisma.BaseDocumentScalarFieldEnum | Prisma.BaseDocumentScalarFieldEnum[]
}

/**
 * BaseDocument findFirstOrThrow
 */
export type BaseDocumentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BaseDocument
   */
  select?: Prisma.BaseDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BaseDocument
   */
  omit?: Prisma.BaseDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BaseDocumentInclude<ExtArgs> | null
  /**
   * Filter, which BaseDocument to fetch.
   */
  where?: Prisma.BaseDocumentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BaseDocuments to fetch.
   */
  orderBy?: Prisma.BaseDocumentOrderByWithRelationInput | Prisma.BaseDocumentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BaseDocuments.
   */
  cursor?: Prisma.BaseDocumentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BaseDocuments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BaseDocuments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BaseDocuments.
   */
  distinct?: Prisma.BaseDocumentScalarFieldEnum | Prisma.BaseDocumentScalarFieldEnum[]
}

/**
 * BaseDocument findMany
 */
export type BaseDocumentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BaseDocument
   */
  select?: Prisma.BaseDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BaseDocument
   */
  omit?: Prisma.BaseDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BaseDocumentInclude<ExtArgs> | null
  /**
   * Filter, which BaseDocuments to fetch.
   */
  where?: Prisma.BaseDocumentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BaseDocuments to fetch.
   */
  orderBy?: Prisma.BaseDocumentOrderByWithRelationInput | Prisma.BaseDocumentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BaseDocuments.
   */
  cursor?: Prisma.BaseDocumentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BaseDocuments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BaseDocuments.
   */
  skip?: number
  distinct?: Prisma.BaseDocumentScalarFieldEnum | Prisma.BaseDocumentScalarFieldEnum[]
}

/**
 * BaseDocument create
 */
export type BaseDocumentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BaseDocument
   */
  select?: Prisma.BaseDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BaseDocument
   */
  omit?: Prisma.BaseDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BaseDocumentInclude<ExtArgs> | null
  /**
   * The data needed to create a BaseDocument.
   */
  data: Prisma.XOR<Prisma.BaseDocumentCreateInput, Prisma.BaseDocumentUncheckedCreateInput>
}

/**
 * BaseDocument createMany
 */
export type BaseDocumentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BaseDocuments.
   */
  data: Prisma.BaseDocumentCreateManyInput | Prisma.BaseDocumentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BaseDocument createManyAndReturn
 */
export type BaseDocumentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BaseDocument
   */
  select?: Prisma.BaseDocumentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BaseDocument
   */
  omit?: Prisma.BaseDocumentOmit<ExtArgs> | null
  /**
   * The data used to create many BaseDocuments.
   */
  data: Prisma.BaseDocumentCreateManyInput | Prisma.BaseDocumentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BaseDocumentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BaseDocument update
 */
export type BaseDocumentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BaseDocument
   */
  select?: Prisma.BaseDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BaseDocument
   */
  omit?: Prisma.BaseDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BaseDocumentInclude<ExtArgs> | null
  /**
   * The data needed to update a BaseDocument.
   */
  data: Prisma.XOR<Prisma.BaseDocumentUpdateInput, Prisma.BaseDocumentUncheckedUpdateInput>
  /**
   * Choose, which BaseDocument to update.
   */
  where: Prisma.BaseDocumentWhereUniqueInput
}

/**
 * BaseDocument updateMany
 */
export type BaseDocumentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BaseDocuments.
   */
  data: Prisma.XOR<Prisma.BaseDocumentUpdateManyMutationInput, Prisma.BaseDocumentUncheckedUpdateManyInput>
  /**
   * Filter which BaseDocuments to update
   */
  where?: Prisma.BaseDocumentWhereInput
  /**
   * Limit how many BaseDocuments to update.
   */
  limit?: number
}

/**
 * BaseDocument updateManyAndReturn
 */
export type BaseDocumentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BaseDocument
   */
  select?: Prisma.BaseDocumentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BaseDocument
   */
  omit?: Prisma.BaseDocumentOmit<ExtArgs> | null
  /**
   * The data used to update BaseDocuments.
   */
  data: Prisma.XOR<Prisma.BaseDocumentUpdateManyMutationInput, Prisma.BaseDocumentUncheckedUpdateManyInput>
  /**
   * Filter which BaseDocuments to update
   */
  where?: Prisma.BaseDocumentWhereInput
  /**
   * Limit how many BaseDocuments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BaseDocumentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BaseDocument upsert
 */
export type BaseDocumentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BaseDocument
   */
  select?: Prisma.BaseDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BaseDocument
   */
  omit?: Prisma.BaseDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BaseDocumentInclude<ExtArgs> | null
  /**
   * The filter to search for the BaseDocument to update in case it exists.
   */
  where: Prisma.BaseDocumentWhereUniqueInput
  /**
   * In case the BaseDocument found by the `where` argument doesn't exist, create a new BaseDocument with this data.
   */
  create: Prisma.XOR<Prisma.BaseDocumentCreateInput, Prisma.BaseDocumentUncheckedCreateInput>
  /**
   * In case the BaseDocument was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BaseDocumentUpdateInput, Prisma.BaseDocumentUncheckedUpdateInput>
}

/**
 * BaseDocument delete
 */
export type BaseDocumentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BaseDocument
   */
  select?: Prisma.BaseDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BaseDocument
   */
  omit?: Prisma.BaseDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BaseDocumentInclude<ExtArgs> | null
  /**
   * Filter which BaseDocument to delete.
   */
  where: Prisma.BaseDocumentWhereUniqueInput
}

/**
 * BaseDocument deleteMany
 */
export type BaseDocumentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BaseDocuments to delete
   */
  where?: Prisma.BaseDocumentWhereInput
  /**
   * Limit how many BaseDocuments to delete.
   */
  limit?: number
}

/**
 * BaseDocument.favorites
 */
export type BaseDocument$favoritesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteDocument
   */
  select?: Prisma.FavoriteDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteDocument
   */
  omit?: Prisma.FavoriteDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteDocumentInclude<ExtArgs> | null
  where?: Prisma.FavoriteDocumentWhereInput
  orderBy?: Prisma.FavoriteDocumentOrderByWithRelationInput | Prisma.FavoriteDocumentOrderByWithRelationInput[]
  cursor?: Prisma.FavoriteDocumentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FavoriteDocumentScalarFieldEnum | Prisma.FavoriteDocumentScalarFieldEnum[]
}

/**
 * BaseDocument.presentation
 */
export type BaseDocument$presentationArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Presentation
   */
  select?: Prisma.PresentationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Presentation
   */
  omit?: Prisma.PresentationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PresentationInclude<ExtArgs> | null
  where?: Prisma.PresentationWhereInput
}

/**
 * BaseDocument without action
 */
export type BaseDocumentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BaseDocument
   */
  select?: Prisma.BaseDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BaseDocument
   */
  omit?: Prisma.BaseDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BaseDocumentInclude<ExtArgs> | null
}
