
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FavoriteDocument` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model FavoriteDocument
 * 
 */
export type FavoriteDocumentModel = runtime.Types.Result.DefaultSelection<Prisma.$FavoriteDocumentPayload>

export type AggregateFavoriteDocument = {
  _count: FavoriteDocumentCountAggregateOutputType | null
  _min: FavoriteDocumentMinAggregateOutputType | null
  _max: FavoriteDocumentMaxAggregateOutputType | null
}

export type FavoriteDocumentMinAggregateOutputType = {
  id: string | null
  documentId: string | null
  userId: string | null
}

export type FavoriteDocumentMaxAggregateOutputType = {
  id: string | null
  documentId: string | null
  userId: string | null
}

export type FavoriteDocumentCountAggregateOutputType = {
  id: number
  documentId: number
  userId: number
  _all: number
}


export type FavoriteDocumentMinAggregateInputType = {
  id?: true
  documentId?: true
  userId?: true
}

export type FavoriteDocumentMaxAggregateInputType = {
  id?: true
  documentId?: true
  userId?: true
}

export type FavoriteDocumentCountAggregateInputType = {
  id?: true
  documentId?: true
  userId?: true
  _all?: true
}

export type FavoriteDocumentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FavoriteDocument to aggregate.
   */
  where?: Prisma.FavoriteDocumentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FavoriteDocuments to fetch.
   */
  orderBy?: Prisma.FavoriteDocumentOrderByWithRelationInput | Prisma.FavoriteDocumentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FavoriteDocumentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FavoriteDocuments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FavoriteDocuments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FavoriteDocuments
  **/
  _count?: true | FavoriteDocumentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FavoriteDocumentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FavoriteDocumentMaxAggregateInputType
}

export type GetFavoriteDocumentAggregateType<T extends FavoriteDocumentAggregateArgs> = {
      [P in keyof T & keyof AggregateFavoriteDocument]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFavoriteDocument[P]>
    : Prisma.GetScalarType<T[P], AggregateFavoriteDocument[P]>
}




export type FavoriteDocumentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FavoriteDocumentWhereInput
  orderBy?: Prisma.FavoriteDocumentOrderByWithAggregationInput | Prisma.FavoriteDocumentOrderByWithAggregationInput[]
  by: Prisma.FavoriteDocumentScalarFieldEnum[] | Prisma.FavoriteDocumentScalarFieldEnum
  having?: Prisma.FavoriteDocumentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FavoriteDocumentCountAggregateInputType | true
  _min?: FavoriteDocumentMinAggregateInputType
  _max?: FavoriteDocumentMaxAggregateInputType
}

export type FavoriteDocumentGroupByOutputType = {
  id: string
  documentId: string
  userId: string
  _count: FavoriteDocumentCountAggregateOutputType | null
  _min: FavoriteDocumentMinAggregateOutputType | null
  _max: FavoriteDocumentMaxAggregateOutputType | null
}

type GetFavoriteDocumentGroupByPayload<T extends FavoriteDocumentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FavoriteDocumentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FavoriteDocumentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FavoriteDocumentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FavoriteDocumentGroupByOutputType[P]>
      }
    >
  >



export type FavoriteDocumentWhereInput = {
  AND?: Prisma.FavoriteDocumentWhereInput | Prisma.FavoriteDocumentWhereInput[]
  OR?: Prisma.FavoriteDocumentWhereInput[]
  NOT?: Prisma.FavoriteDocumentWhereInput | Prisma.FavoriteDocumentWhereInput[]
  id?: Prisma.StringFilter<"FavoriteDocument"> | string
  documentId?: Prisma.StringFilter<"FavoriteDocument"> | string
  userId?: Prisma.StringFilter<"FavoriteDocument"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  document?: Prisma.XOR<Prisma.BaseDocumentScalarRelationFilter, Prisma.BaseDocumentWhereInput>
}

export type FavoriteDocumentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  document?: Prisma.BaseDocumentOrderByWithRelationInput
}

export type FavoriteDocumentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FavoriteDocumentWhereInput | Prisma.FavoriteDocumentWhereInput[]
  OR?: Prisma.FavoriteDocumentWhereInput[]
  NOT?: Prisma.FavoriteDocumentWhereInput | Prisma.FavoriteDocumentWhereInput[]
  documentId?: Prisma.StringFilter<"FavoriteDocument"> | string
  userId?: Prisma.StringFilter<"FavoriteDocument"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  document?: Prisma.XOR<Prisma.BaseDocumentScalarRelationFilter, Prisma.BaseDocumentWhereInput>
}, "id">

export type FavoriteDocumentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.FavoriteDocumentCountOrderByAggregateInput
  _max?: Prisma.FavoriteDocumentMaxOrderByAggregateInput
  _min?: Prisma.FavoriteDocumentMinOrderByAggregateInput
}

export type FavoriteDocumentScalarWhereWithAggregatesInput = {
  AND?: Prisma.FavoriteDocumentScalarWhereWithAggregatesInput | Prisma.FavoriteDocumentScalarWhereWithAggregatesInput[]
  OR?: Prisma.FavoriteDocumentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FavoriteDocumentScalarWhereWithAggregatesInput | Prisma.FavoriteDocumentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FavoriteDocument"> | string
  documentId?: Prisma.StringWithAggregatesFilter<"FavoriteDocument"> | string
  userId?: Prisma.StringWithAggregatesFilter<"FavoriteDocument"> | string
}

export type FavoriteDocumentCreateInput = {
  id?: string
  user: Prisma.UserCreateNestedOneWithoutFavoritesInput
  document: Prisma.BaseDocumentCreateNestedOneWithoutFavoritesInput
}

export type FavoriteDocumentUncheckedCreateInput = {
  id?: string
  documentId: string
  userId: string
}

export type FavoriteDocumentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutFavoritesNestedInput
  document?: Prisma.BaseDocumentUpdateOneRequiredWithoutFavoritesNestedInput
}

export type FavoriteDocumentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  documentId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FavoriteDocumentCreateManyInput = {
  id?: string
  documentId: string
  userId: string
}

export type FavoriteDocumentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FavoriteDocumentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  documentId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FavoriteDocumentListRelationFilter = {
  every?: Prisma.FavoriteDocumentWhereInput
  some?: Prisma.FavoriteDocumentWhereInput
  none?: Prisma.FavoriteDocumentWhereInput
}

export type FavoriteDocumentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FavoriteDocumentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type FavoriteDocumentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type FavoriteDocumentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type FavoriteDocumentCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FavoriteDocumentCreateWithoutUserInput, Prisma.FavoriteDocumentUncheckedCreateWithoutUserInput> | Prisma.FavoriteDocumentCreateWithoutUserInput[] | Prisma.FavoriteDocumentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FavoriteDocumentCreateOrConnectWithoutUserInput | Prisma.FavoriteDocumentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FavoriteDocumentCreateManyUserInputEnvelope
  connect?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
}

export type FavoriteDocumentUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FavoriteDocumentCreateWithoutUserInput, Prisma.FavoriteDocumentUncheckedCreateWithoutUserInput> | Prisma.FavoriteDocumentCreateWithoutUserInput[] | Prisma.FavoriteDocumentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FavoriteDocumentCreateOrConnectWithoutUserInput | Prisma.FavoriteDocumentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FavoriteDocumentCreateManyUserInputEnvelope
  connect?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
}

export type FavoriteDocumentUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FavoriteDocumentCreateWithoutUserInput, Prisma.FavoriteDocumentUncheckedCreateWithoutUserInput> | Prisma.FavoriteDocumentCreateWithoutUserInput[] | Prisma.FavoriteDocumentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FavoriteDocumentCreateOrConnectWithoutUserInput | Prisma.FavoriteDocumentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FavoriteDocumentUpsertWithWhereUniqueWithoutUserInput | Prisma.FavoriteDocumentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FavoriteDocumentCreateManyUserInputEnvelope
  set?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  disconnect?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  delete?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  connect?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  update?: Prisma.FavoriteDocumentUpdateWithWhereUniqueWithoutUserInput | Prisma.FavoriteDocumentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FavoriteDocumentUpdateManyWithWhereWithoutUserInput | Prisma.FavoriteDocumentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FavoriteDocumentScalarWhereInput | Prisma.FavoriteDocumentScalarWhereInput[]
}

export type FavoriteDocumentUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FavoriteDocumentCreateWithoutUserInput, Prisma.FavoriteDocumentUncheckedCreateWithoutUserInput> | Prisma.FavoriteDocumentCreateWithoutUserInput[] | Prisma.FavoriteDocumentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FavoriteDocumentCreateOrConnectWithoutUserInput | Prisma.FavoriteDocumentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FavoriteDocumentUpsertWithWhereUniqueWithoutUserInput | Prisma.FavoriteDocumentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FavoriteDocumentCreateManyUserInputEnvelope
  set?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  disconnect?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  delete?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  connect?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  update?: Prisma.FavoriteDocumentUpdateWithWhereUniqueWithoutUserInput | Prisma.FavoriteDocumentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FavoriteDocumentUpdateManyWithWhereWithoutUserInput | Prisma.FavoriteDocumentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FavoriteDocumentScalarWhereInput | Prisma.FavoriteDocumentScalarWhereInput[]
}

export type FavoriteDocumentCreateNestedManyWithoutDocumentInput = {
  create?: Prisma.XOR<Prisma.FavoriteDocumentCreateWithoutDocumentInput, Prisma.FavoriteDocumentUncheckedCreateWithoutDocumentInput> | Prisma.FavoriteDocumentCreateWithoutDocumentInput[] | Prisma.FavoriteDocumentUncheckedCreateWithoutDocumentInput[]
  connectOrCreate?: Prisma.FavoriteDocumentCreateOrConnectWithoutDocumentInput | Prisma.FavoriteDocumentCreateOrConnectWithoutDocumentInput[]
  createMany?: Prisma.FavoriteDocumentCreateManyDocumentInputEnvelope
  connect?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
}

export type FavoriteDocumentUncheckedCreateNestedManyWithoutDocumentInput = {
  create?: Prisma.XOR<Prisma.FavoriteDocumentCreateWithoutDocumentInput, Prisma.FavoriteDocumentUncheckedCreateWithoutDocumentInput> | Prisma.FavoriteDocumentCreateWithoutDocumentInput[] | Prisma.FavoriteDocumentUncheckedCreateWithoutDocumentInput[]
  connectOrCreate?: Prisma.FavoriteDocumentCreateOrConnectWithoutDocumentInput | Prisma.FavoriteDocumentCreateOrConnectWithoutDocumentInput[]
  createMany?: Prisma.FavoriteDocumentCreateManyDocumentInputEnvelope
  connect?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
}

export type FavoriteDocumentUpdateManyWithoutDocumentNestedInput = {
  create?: Prisma.XOR<Prisma.FavoriteDocumentCreateWithoutDocumentInput, Prisma.FavoriteDocumentUncheckedCreateWithoutDocumentInput> | Prisma.FavoriteDocumentCreateWithoutDocumentInput[] | Prisma.FavoriteDocumentUncheckedCreateWithoutDocumentInput[]
  connectOrCreate?: Prisma.FavoriteDocumentCreateOrConnectWithoutDocumentInput | Prisma.FavoriteDocumentCreateOrConnectWithoutDocumentInput[]
  upsert?: Prisma.FavoriteDocumentUpsertWithWhereUniqueWithoutDocumentInput | Prisma.FavoriteDocumentUpsertWithWhereUniqueWithoutDocumentInput[]
  createMany?: Prisma.FavoriteDocumentCreateManyDocumentInputEnvelope
  set?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  disconnect?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  delete?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  connect?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  update?: Prisma.FavoriteDocumentUpdateWithWhereUniqueWithoutDocumentInput | Prisma.FavoriteDocumentUpdateWithWhereUniqueWithoutDocumentInput[]
  updateMany?: Prisma.FavoriteDocumentUpdateManyWithWhereWithoutDocumentInput | Prisma.FavoriteDocumentUpdateManyWithWhereWithoutDocumentInput[]
  deleteMany?: Prisma.FavoriteDocumentScalarWhereInput | Prisma.FavoriteDocumentScalarWhereInput[]
}

export type FavoriteDocumentUncheckedUpdateManyWithoutDocumentNestedInput = {
  create?: Prisma.XOR<Prisma.FavoriteDocumentCreateWithoutDocumentInput, Prisma.FavoriteDocumentUncheckedCreateWithoutDocumentInput> | Prisma.FavoriteDocumentCreateWithoutDocumentInput[] | Prisma.FavoriteDocumentUncheckedCreateWithoutDocumentInput[]
  connectOrCreate?: Prisma.FavoriteDocumentCreateOrConnectWithoutDocumentInput | Prisma.FavoriteDocumentCreateOrConnectWithoutDocumentInput[]
  upsert?: Prisma.FavoriteDocumentUpsertWithWhereUniqueWithoutDocumentInput | Prisma.FavoriteDocumentUpsertWithWhereUniqueWithoutDocumentInput[]
  createMany?: Prisma.FavoriteDocumentCreateManyDocumentInputEnvelope
  set?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  disconnect?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  delete?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  connect?: Prisma.FavoriteDocumentWhereUniqueInput | Prisma.FavoriteDocumentWhereUniqueInput[]
  update?: Prisma.FavoriteDocumentUpdateWithWhereUniqueWithoutDocumentInput | Prisma.FavoriteDocumentUpdateWithWhereUniqueWithoutDocumentInput[]
  updateMany?: Prisma.FavoriteDocumentUpdateManyWithWhereWithoutDocumentInput | Prisma.FavoriteDocumentUpdateManyWithWhereWithoutDocumentInput[]
  deleteMany?: Prisma.FavoriteDocumentScalarWhereInput | Prisma.FavoriteDocumentScalarWhereInput[]
}

export type FavoriteDocumentCreateWithoutUserInput = {
  id?: string
  document: Prisma.BaseDocumentCreateNestedOneWithoutFavoritesInput
}

export type FavoriteDocumentUncheckedCreateWithoutUserInput = {
  id?: string
  documentId: string
}

export type FavoriteDocumentCreateOrConnectWithoutUserInput = {
  where: Prisma.FavoriteDocumentWhereUniqueInput
  create: Prisma.XOR<Prisma.FavoriteDocumentCreateWithoutUserInput, Prisma.FavoriteDocumentUncheckedCreateWithoutUserInput>
}

export type FavoriteDocumentCreateManyUserInputEnvelope = {
  data: Prisma.FavoriteDocumentCreateManyUserInput | Prisma.FavoriteDocumentCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type FavoriteDocumentUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.FavoriteDocumentWhereUniqueInput
  update: Prisma.XOR<Prisma.FavoriteDocumentUpdateWithoutUserInput, Prisma.FavoriteDocumentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.FavoriteDocumentCreateWithoutUserInput, Prisma.FavoriteDocumentUncheckedCreateWithoutUserInput>
}

export type FavoriteDocumentUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.FavoriteDocumentWhereUniqueInput
  data: Prisma.XOR<Prisma.FavoriteDocumentUpdateWithoutUserInput, Prisma.FavoriteDocumentUncheckedUpdateWithoutUserInput>
}

export type FavoriteDocumentUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.FavoriteDocumentScalarWhereInput
  data: Prisma.XOR<Prisma.FavoriteDocumentUpdateManyMutationInput, Prisma.FavoriteDocumentUncheckedUpdateManyWithoutUserInput>
}

export type FavoriteDocumentScalarWhereInput = {
  AND?: Prisma.FavoriteDocumentScalarWhereInput | Prisma.FavoriteDocumentScalarWhereInput[]
  OR?: Prisma.FavoriteDocumentScalarWhereInput[]
  NOT?: Prisma.FavoriteDocumentScalarWhereInput | Prisma.FavoriteDocumentScalarWhereInput[]
  id?: Prisma.StringFilter<"FavoriteDocument"> | string
  documentId?: Prisma.StringFilter<"FavoriteDocument"> | string
  userId?: Prisma.StringFilter<"FavoriteDocument"> | string
}

export type FavoriteDocumentCreateWithoutDocumentInput = {
  id?: string
  user: Prisma.UserCreateNestedOneWithoutFavoritesInput
}

export type FavoriteDocumentUncheckedCreateWithoutDocumentInput = {
  id?: string
  userId: string
}

export type FavoriteDocumentCreateOrConnectWithoutDocumentInput = {
  where: Prisma.FavoriteDocumentWhereUniqueInput
  create: Prisma.XOR<Prisma.FavoriteDocumentCreateWithoutDocumentInput, Prisma.FavoriteDocumentUncheckedCreateWithoutDocumentInput>
}

export type FavoriteDocumentCreateManyDocumentInputEnvelope = {
  data: Prisma.FavoriteDocumentCreateManyDocumentInput | Prisma.FavoriteDocumentCreateManyDocumentInput[]
  skipDuplicates?: boolean
}

export type FavoriteDocumentUpsertWithWhereUniqueWithoutDocumentInput = {
  where: Prisma.FavoriteDocumentWhereUniqueInput
  update: Prisma.XOR<Prisma.FavoriteDocumentUpdateWithoutDocumentInput, Prisma.FavoriteDocumentUncheckedUpdateWithoutDocumentInput>
  create: Prisma.XOR<Prisma.FavoriteDocumentCreateWithoutDocumentInput, Prisma.FavoriteDocumentUncheckedCreateWithoutDocumentInput>
}

export type FavoriteDocumentUpdateWithWhereUniqueWithoutDocumentInput = {
  where: Prisma.FavoriteDocumentWhereUniqueInput
  data: Prisma.XOR<Prisma.FavoriteDocumentUpdateWithoutDocumentInput, Prisma.FavoriteDocumentUncheckedUpdateWithoutDocumentInput>
}

export type FavoriteDocumentUpdateManyWithWhereWithoutDocumentInput = {
  where: Prisma.FavoriteDocumentScalarWhereInput
  data: Prisma.XOR<Prisma.FavoriteDocumentUpdateManyMutationInput, Prisma.FavoriteDocumentUncheckedUpdateManyWithoutDocumentInput>
}

export type FavoriteDocumentCreateManyUserInput = {
  id?: string
  documentId: string
}

export type FavoriteDocumentUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  document?: Prisma.BaseDocumentUpdateOneRequiredWithoutFavoritesNestedInput
}

export type FavoriteDocumentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  documentId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FavoriteDocumentUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  documentId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FavoriteDocumentCreateManyDocumentInput = {
  id?: string
  userId: string
}

export type FavoriteDocumentUpdateWithoutDocumentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutFavoritesNestedInput
}

export type FavoriteDocumentUncheckedUpdateWithoutDocumentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FavoriteDocumentUncheckedUpdateManyWithoutDocumentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type FavoriteDocumentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  documentId?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  document?: boolean | Prisma.BaseDocumentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["favoriteDocument"]>

export type FavoriteDocumentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  documentId?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  document?: boolean | Prisma.BaseDocumentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["favoriteDocument"]>

export type FavoriteDocumentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  documentId?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  document?: boolean | Prisma.BaseDocumentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["favoriteDocument"]>

export type FavoriteDocumentSelectScalar = {
  id?: boolean
  documentId?: boolean
  userId?: boolean
}

export type FavoriteDocumentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "documentId" | "userId", ExtArgs["result"]["favoriteDocument"]>
export type FavoriteDocumentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  document?: boolean | Prisma.BaseDocumentDefaultArgs<ExtArgs>
}
export type FavoriteDocumentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  document?: boolean | Prisma.BaseDocumentDefaultArgs<ExtArgs>
}
export type FavoriteDocumentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  document?: boolean | Prisma.BaseDocumentDefaultArgs<ExtArgs>
}

export type $FavoriteDocumentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FavoriteDocument"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    document: Prisma.$BaseDocumentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    documentId: string
    userId: string
  }, ExtArgs["result"]["favoriteDocument"]>
  composites: {}
}

export type FavoriteDocumentGetPayload<S extends boolean | null | undefined | FavoriteDocumentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FavoriteDocumentPayload, S>

export type FavoriteDocumentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FavoriteDocumentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FavoriteDocumentCountAggregateInputType | true
  }

export interface FavoriteDocumentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FavoriteDocument'], meta: { name: 'FavoriteDocument' } }
  /**
   * Find zero or one FavoriteDocument that matches the filter.
   * @param {FavoriteDocumentFindUniqueArgs} args - Arguments to find a FavoriteDocument
   * @example
   * // Get one FavoriteDocument
   * const favoriteDocument = await prisma.favoriteDocument.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FavoriteDocumentFindUniqueArgs>(args: Prisma.SelectSubset<T, FavoriteDocumentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FavoriteDocumentClient<runtime.Types.Result.GetResult<Prisma.$FavoriteDocumentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FavoriteDocument that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FavoriteDocumentFindUniqueOrThrowArgs} args - Arguments to find a FavoriteDocument
   * @example
   * // Get one FavoriteDocument
   * const favoriteDocument = await prisma.favoriteDocument.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FavoriteDocumentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FavoriteDocumentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FavoriteDocumentClient<runtime.Types.Result.GetResult<Prisma.$FavoriteDocumentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FavoriteDocument that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteDocumentFindFirstArgs} args - Arguments to find a FavoriteDocument
   * @example
   * // Get one FavoriteDocument
   * const favoriteDocument = await prisma.favoriteDocument.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FavoriteDocumentFindFirstArgs>(args?: Prisma.SelectSubset<T, FavoriteDocumentFindFirstArgs<ExtArgs>>): Prisma.Prisma__FavoriteDocumentClient<runtime.Types.Result.GetResult<Prisma.$FavoriteDocumentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FavoriteDocument that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteDocumentFindFirstOrThrowArgs} args - Arguments to find a FavoriteDocument
   * @example
   * // Get one FavoriteDocument
   * const favoriteDocument = await prisma.favoriteDocument.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FavoriteDocumentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FavoriteDocumentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FavoriteDocumentClient<runtime.Types.Result.GetResult<Prisma.$FavoriteDocumentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FavoriteDocuments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteDocumentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FavoriteDocuments
   * const favoriteDocuments = await prisma.favoriteDocument.findMany()
   * 
   * // Get first 10 FavoriteDocuments
   * const favoriteDocuments = await prisma.favoriteDocument.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const favoriteDocumentWithIdOnly = await prisma.favoriteDocument.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FavoriteDocumentFindManyArgs>(args?: Prisma.SelectSubset<T, FavoriteDocumentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FavoriteDocumentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FavoriteDocument.
   * @param {FavoriteDocumentCreateArgs} args - Arguments to create a FavoriteDocument.
   * @example
   * // Create one FavoriteDocument
   * const FavoriteDocument = await prisma.favoriteDocument.create({
   *   data: {
   *     // ... data to create a FavoriteDocument
   *   }
   * })
   * 
   */
  create<T extends FavoriteDocumentCreateArgs>(args: Prisma.SelectSubset<T, FavoriteDocumentCreateArgs<ExtArgs>>): Prisma.Prisma__FavoriteDocumentClient<runtime.Types.Result.GetResult<Prisma.$FavoriteDocumentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FavoriteDocuments.
   * @param {FavoriteDocumentCreateManyArgs} args - Arguments to create many FavoriteDocuments.
   * @example
   * // Create many FavoriteDocuments
   * const favoriteDocument = await prisma.favoriteDocument.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FavoriteDocumentCreateManyArgs>(args?: Prisma.SelectSubset<T, FavoriteDocumentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FavoriteDocuments and returns the data saved in the database.
   * @param {FavoriteDocumentCreateManyAndReturnArgs} args - Arguments to create many FavoriteDocuments.
   * @example
   * // Create many FavoriteDocuments
   * const favoriteDocument = await prisma.favoriteDocument.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FavoriteDocuments and only return the `id`
   * const favoriteDocumentWithIdOnly = await prisma.favoriteDocument.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FavoriteDocumentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FavoriteDocumentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FavoriteDocumentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FavoriteDocument.
   * @param {FavoriteDocumentDeleteArgs} args - Arguments to delete one FavoriteDocument.
   * @example
   * // Delete one FavoriteDocument
   * const FavoriteDocument = await prisma.favoriteDocument.delete({
   *   where: {
   *     // ... filter to delete one FavoriteDocument
   *   }
   * })
   * 
   */
  delete<T extends FavoriteDocumentDeleteArgs>(args: Prisma.SelectSubset<T, FavoriteDocumentDeleteArgs<ExtArgs>>): Prisma.Prisma__FavoriteDocumentClient<runtime.Types.Result.GetResult<Prisma.$FavoriteDocumentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FavoriteDocument.
   * @param {FavoriteDocumentUpdateArgs} args - Arguments to update one FavoriteDocument.
   * @example
   * // Update one FavoriteDocument
   * const favoriteDocument = await prisma.favoriteDocument.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FavoriteDocumentUpdateArgs>(args: Prisma.SelectSubset<T, FavoriteDocumentUpdateArgs<ExtArgs>>): Prisma.Prisma__FavoriteDocumentClient<runtime.Types.Result.GetResult<Prisma.$FavoriteDocumentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FavoriteDocuments.
   * @param {FavoriteDocumentDeleteManyArgs} args - Arguments to filter FavoriteDocuments to delete.
   * @example
   * // Delete a few FavoriteDocuments
   * const { count } = await prisma.favoriteDocument.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FavoriteDocumentDeleteManyArgs>(args?: Prisma.SelectSubset<T, FavoriteDocumentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FavoriteDocuments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteDocumentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FavoriteDocuments
   * const favoriteDocument = await prisma.favoriteDocument.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FavoriteDocumentUpdateManyArgs>(args: Prisma.SelectSubset<T, FavoriteDocumentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FavoriteDocuments and returns the data updated in the database.
   * @param {FavoriteDocumentUpdateManyAndReturnArgs} args - Arguments to update many FavoriteDocuments.
   * @example
   * // Update many FavoriteDocuments
   * const favoriteDocument = await prisma.favoriteDocument.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FavoriteDocuments and only return the `id`
   * const favoriteDocumentWithIdOnly = await prisma.favoriteDocument.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FavoriteDocumentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FavoriteDocumentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FavoriteDocumentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FavoriteDocument.
   * @param {FavoriteDocumentUpsertArgs} args - Arguments to update or create a FavoriteDocument.
   * @example
   * // Update or create a FavoriteDocument
   * const favoriteDocument = await prisma.favoriteDocument.upsert({
   *   create: {
   *     // ... data to create a FavoriteDocument
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FavoriteDocument we want to update
   *   }
   * })
   */
  upsert<T extends FavoriteDocumentUpsertArgs>(args: Prisma.SelectSubset<T, FavoriteDocumentUpsertArgs<ExtArgs>>): Prisma.Prisma__FavoriteDocumentClient<runtime.Types.Result.GetResult<Prisma.$FavoriteDocumentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FavoriteDocuments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteDocumentCountArgs} args - Arguments to filter FavoriteDocuments to count.
   * @example
   * // Count the number of FavoriteDocuments
   * const count = await prisma.favoriteDocument.count({
   *   where: {
   *     // ... the filter for the FavoriteDocuments we want to count
   *   }
   * })
  **/
  count<T extends FavoriteDocumentCountArgs>(
    args?: Prisma.Subset<T, FavoriteDocumentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FavoriteDocumentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FavoriteDocument.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteDocumentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FavoriteDocumentAggregateArgs>(args: Prisma.Subset<T, FavoriteDocumentAggregateArgs>): Prisma.PrismaPromise<GetFavoriteDocumentAggregateType<T>>

  /**
   * Group by FavoriteDocument.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteDocumentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FavoriteDocumentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FavoriteDocumentGroupByArgs['orderBy'] }
      : { orderBy?: FavoriteDocumentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FavoriteDocumentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFavoriteDocumentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FavoriteDocument model
 */
readonly fields: FavoriteDocumentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FavoriteDocument.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FavoriteDocumentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  document<T extends Prisma.BaseDocumentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BaseDocumentDefaultArgs<ExtArgs>>): Prisma.Prisma__BaseDocumentClient<runtime.Types.Result.GetResult<Prisma.$BaseDocumentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FavoriteDocument model
 */
export interface FavoriteDocumentFieldRefs {
  readonly id: Prisma.FieldRef<"FavoriteDocument", 'String'>
  readonly documentId: Prisma.FieldRef<"FavoriteDocument", 'String'>
  readonly userId: Prisma.FieldRef<"FavoriteDocument", 'String'>
}
    

// Custom InputTypes
/**
 * FavoriteDocument findUnique
 */
export type FavoriteDocumentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteDocument
   */
  select?: Prisma.FavoriteDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteDocument
   */
  omit?: Prisma.FavoriteDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteDocumentInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteDocument to fetch.
   */
  where: Prisma.FavoriteDocumentWhereUniqueInput
}

/**
 * FavoriteDocument findUniqueOrThrow
 */
export type FavoriteDocumentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteDocument
   */
  select?: Prisma.FavoriteDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteDocument
   */
  omit?: Prisma.FavoriteDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteDocumentInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteDocument to fetch.
   */
  where: Prisma.FavoriteDocumentWhereUniqueInput
}

/**
 * FavoriteDocument findFirst
 */
export type FavoriteDocumentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteDocument
   */
  select?: Prisma.FavoriteDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteDocument
   */
  omit?: Prisma.FavoriteDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteDocumentInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteDocument to fetch.
   */
  where?: Prisma.FavoriteDocumentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FavoriteDocuments to fetch.
   */
  orderBy?: Prisma.FavoriteDocumentOrderByWithRelationInput | Prisma.FavoriteDocumentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FavoriteDocuments.
   */
  cursor?: Prisma.FavoriteDocumentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FavoriteDocuments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FavoriteDocuments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FavoriteDocuments.
   */
  distinct?: Prisma.FavoriteDocumentScalarFieldEnum | Prisma.FavoriteDocumentScalarFieldEnum[]
}

/**
 * FavoriteDocument findFirstOrThrow
 */
export type FavoriteDocumentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteDocument
   */
  select?: Prisma.FavoriteDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteDocument
   */
  omit?: Prisma.FavoriteDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteDocumentInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteDocument to fetch.
   */
  where?: Prisma.FavoriteDocumentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FavoriteDocuments to fetch.
   */
  orderBy?: Prisma.FavoriteDocumentOrderByWithRelationInput | Prisma.FavoriteDocumentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FavoriteDocuments.
   */
  cursor?: Prisma.FavoriteDocumentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FavoriteDocuments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FavoriteDocuments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FavoriteDocuments.
   */
  distinct?: Prisma.FavoriteDocumentScalarFieldEnum | Prisma.FavoriteDocumentScalarFieldEnum[]
}

/**
 * FavoriteDocument findMany
 */
export type FavoriteDocumentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteDocument
   */
  select?: Prisma.FavoriteDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteDocument
   */
  omit?: Prisma.FavoriteDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteDocumentInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteDocuments to fetch.
   */
  where?: Prisma.FavoriteDocumentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FavoriteDocuments to fetch.
   */
  orderBy?: Prisma.FavoriteDocumentOrderByWithRelationInput | Prisma.FavoriteDocumentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FavoriteDocuments.
   */
  cursor?: Prisma.FavoriteDocumentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FavoriteDocuments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FavoriteDocuments.
   */
  skip?: number
  distinct?: Prisma.FavoriteDocumentScalarFieldEnum | Prisma.FavoriteDocumentScalarFieldEnum[]
}

/**
 * FavoriteDocument create
 */
export type FavoriteDocumentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteDocument
   */
  select?: Prisma.FavoriteDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteDocument
   */
  omit?: Prisma.FavoriteDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteDocumentInclude<ExtArgs> | null
  /**
   * The data needed to create a FavoriteDocument.
   */
  data: Prisma.XOR<Prisma.FavoriteDocumentCreateInput, Prisma.FavoriteDocumentUncheckedCreateInput>
}

/**
 * FavoriteDocument createMany
 */
export type FavoriteDocumentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FavoriteDocuments.
   */
  data: Prisma.FavoriteDocumentCreateManyInput | Prisma.FavoriteDocumentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FavoriteDocument createManyAndReturn
 */
export type FavoriteDocumentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteDocument
   */
  select?: Prisma.FavoriteDocumentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteDocument
   */
  omit?: Prisma.FavoriteDocumentOmit<ExtArgs> | null
  /**
   * The data used to create many FavoriteDocuments.
   */
  data: Prisma.FavoriteDocumentCreateManyInput | Prisma.FavoriteDocumentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteDocumentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FavoriteDocument update
 */
export type FavoriteDocumentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteDocument
   */
  select?: Prisma.FavoriteDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteDocument
   */
  omit?: Prisma.FavoriteDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteDocumentInclude<ExtArgs> | null
  /**
   * The data needed to update a FavoriteDocument.
   */
  data: Prisma.XOR<Prisma.FavoriteDocumentUpdateInput, Prisma.FavoriteDocumentUncheckedUpdateInput>
  /**
   * Choose, which FavoriteDocument to update.
   */
  where: Prisma.FavoriteDocumentWhereUniqueInput
}

/**
 * FavoriteDocument updateMany
 */
export type FavoriteDocumentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FavoriteDocuments.
   */
  data: Prisma.XOR<Prisma.FavoriteDocumentUpdateManyMutationInput, Prisma.FavoriteDocumentUncheckedUpdateManyInput>
  /**
   * Filter which FavoriteDocuments to update
   */
  where?: Prisma.FavoriteDocumentWhereInput
  /**
   * Limit how many FavoriteDocuments to update.
   */
  limit?: number
}

/**
 * FavoriteDocument updateManyAndReturn
 */
export type FavoriteDocumentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteDocument
   */
  select?: Prisma.FavoriteDocumentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteDocument
   */
  omit?: Prisma.FavoriteDocumentOmit<ExtArgs> | null
  /**
   * The data used to update FavoriteDocuments.
   */
  data: Prisma.XOR<Prisma.FavoriteDocumentUpdateManyMutationInput, Prisma.FavoriteDocumentUncheckedUpdateManyInput>
  /**
   * Filter which FavoriteDocuments to update
   */
  where?: Prisma.FavoriteDocumentWhereInput
  /**
   * Limit how many FavoriteDocuments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteDocumentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FavoriteDocument upsert
 */
export type FavoriteDocumentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteDocument
   */
  select?: Prisma.FavoriteDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteDocument
   */
  omit?: Prisma.FavoriteDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteDocumentInclude<ExtArgs> | null
  /**
   * The filter to search for the FavoriteDocument to update in case it exists.
   */
  where: Prisma.FavoriteDocumentWhereUniqueInput
  /**
   * In case the FavoriteDocument found by the `where` argument doesn't exist, create a new FavoriteDocument with this data.
   */
  create: Prisma.XOR<Prisma.FavoriteDocumentCreateInput, Prisma.FavoriteDocumentUncheckedCreateInput>
  /**
   * In case the FavoriteDocument was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FavoriteDocumentUpdateInput, Prisma.FavoriteDocumentUncheckedUpdateInput>
}

/**
 * FavoriteDocument delete
 */
export type FavoriteDocumentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteDocument
   */
  select?: Prisma.FavoriteDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteDocument
   */
  omit?: Prisma.FavoriteDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteDocumentInclude<ExtArgs> | null
  /**
   * Filter which FavoriteDocument to delete.
   */
  where: Prisma.FavoriteDocumentWhereUniqueInput
}

/**
 * FavoriteDocument deleteMany
 */
export type FavoriteDocumentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FavoriteDocuments to delete
   */
  where?: Prisma.FavoriteDocumentWhereInput
  /**
   * Limit how many FavoriteDocuments to delete.
   */
  limit?: number
}

/**
 * FavoriteDocument without action
 */
export type FavoriteDocumentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteDocument
   */
  select?: Prisma.FavoriteDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteDocument
   */
  omit?: Prisma.FavoriteDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteDocumentInclude<ExtArgs> | null
}
