
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ImageLibrary` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ImageLibrary
 * 
 */
export type ImageLibraryModel = runtime.Types.Result.DefaultSelection<Prisma.$ImageLibraryPayload>

export type AggregateImageLibrary = {
  _count: ImageLibraryCountAggregateOutputType | null
  _min: ImageLibraryMinAggregateOutputType | null
  _max: ImageLibraryMaxAggregateOutputType | null
}

export type ImageLibraryMinAggregateOutputType = {
  id: string | null
  url: string | null
  type: $Enums.ImageLibraryType | null
  prompt: string | null
  provider: string | null
  modelId: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ImageLibraryMaxAggregateOutputType = {
  id: string | null
  url: string | null
  type: $Enums.ImageLibraryType | null
  prompt: string | null
  provider: string | null
  modelId: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ImageLibraryCountAggregateOutputType = {
  id: number
  url: number
  type: number
  prompt: number
  provider: number
  modelId: number
  userId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ImageLibraryMinAggregateInputType = {
  id?: true
  url?: true
  type?: true
  prompt?: true
  provider?: true
  modelId?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type ImageLibraryMaxAggregateInputType = {
  id?: true
  url?: true
  type?: true
  prompt?: true
  provider?: true
  modelId?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type ImageLibraryCountAggregateInputType = {
  id?: true
  url?: true
  type?: true
  prompt?: true
  provider?: true
  modelId?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ImageLibraryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ImageLibrary to aggregate.
   */
  where?: Prisma.ImageLibraryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ImageLibraries to fetch.
   */
  orderBy?: Prisma.ImageLibraryOrderByWithRelationInput | Prisma.ImageLibraryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ImageLibraryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ImageLibraries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ImageLibraries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ImageLibraries
  **/
  _count?: true | ImageLibraryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ImageLibraryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ImageLibraryMaxAggregateInputType
}

export type GetImageLibraryAggregateType<T extends ImageLibraryAggregateArgs> = {
      [P in keyof T & keyof AggregateImageLibrary]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateImageLibrary[P]>
    : Prisma.GetScalarType<T[P], AggregateImageLibrary[P]>
}




export type ImageLibraryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ImageLibraryWhereInput
  orderBy?: Prisma.ImageLibraryOrderByWithAggregationInput | Prisma.ImageLibraryOrderByWithAggregationInput[]
  by: Prisma.ImageLibraryScalarFieldEnum[] | Prisma.ImageLibraryScalarFieldEnum
  having?: Prisma.ImageLibraryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ImageLibraryCountAggregateInputType | true
  _min?: ImageLibraryMinAggregateInputType
  _max?: ImageLibraryMaxAggregateInputType
}

export type ImageLibraryGroupByOutputType = {
  id: string
  url: string
  type: $Enums.ImageLibraryType
  prompt: string | null
  provider: string | null
  modelId: string | null
  userId: string
  createdAt: Date
  updatedAt: Date
  _count: ImageLibraryCountAggregateOutputType | null
  _min: ImageLibraryMinAggregateOutputType | null
  _max: ImageLibraryMaxAggregateOutputType | null
}

type GetImageLibraryGroupByPayload<T extends ImageLibraryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ImageLibraryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ImageLibraryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ImageLibraryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ImageLibraryGroupByOutputType[P]>
      }
    >
  >



export type ImageLibraryWhereInput = {
  AND?: Prisma.ImageLibraryWhereInput | Prisma.ImageLibraryWhereInput[]
  OR?: Prisma.ImageLibraryWhereInput[]
  NOT?: Prisma.ImageLibraryWhereInput | Prisma.ImageLibraryWhereInput[]
  id?: Prisma.StringFilter<"ImageLibrary"> | string
  url?: Prisma.StringFilter<"ImageLibrary"> | string
  type?: Prisma.EnumImageLibraryTypeFilter<"ImageLibrary"> | $Enums.ImageLibraryType
  prompt?: Prisma.StringNullableFilter<"ImageLibrary"> | string | null
  provider?: Prisma.StringNullableFilter<"ImageLibrary"> | string | null
  modelId?: Prisma.StringNullableFilter<"ImageLibrary"> | string | null
  userId?: Prisma.StringFilter<"ImageLibrary"> | string
  createdAt?: Prisma.DateTimeFilter<"ImageLibrary"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ImageLibrary"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ImageLibraryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  type?: Prisma.SortOrder
  prompt?: Prisma.SortOrderInput | Prisma.SortOrder
  provider?: Prisma.SortOrderInput | Prisma.SortOrder
  modelId?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type ImageLibraryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ImageLibraryWhereInput | Prisma.ImageLibraryWhereInput[]
  OR?: Prisma.ImageLibraryWhereInput[]
  NOT?: Prisma.ImageLibraryWhereInput | Prisma.ImageLibraryWhereInput[]
  url?: Prisma.StringFilter<"ImageLibrary"> | string
  type?: Prisma.EnumImageLibraryTypeFilter<"ImageLibrary"> | $Enums.ImageLibraryType
  prompt?: Prisma.StringNullableFilter<"ImageLibrary"> | string | null
  provider?: Prisma.StringNullableFilter<"ImageLibrary"> | string | null
  modelId?: Prisma.StringNullableFilter<"ImageLibrary"> | string | null
  userId?: Prisma.StringFilter<"ImageLibrary"> | string
  createdAt?: Prisma.DateTimeFilter<"ImageLibrary"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ImageLibrary"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type ImageLibraryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  type?: Prisma.SortOrder
  prompt?: Prisma.SortOrderInput | Prisma.SortOrder
  provider?: Prisma.SortOrderInput | Prisma.SortOrder
  modelId?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ImageLibraryCountOrderByAggregateInput
  _max?: Prisma.ImageLibraryMaxOrderByAggregateInput
  _min?: Prisma.ImageLibraryMinOrderByAggregateInput
}

export type ImageLibraryScalarWhereWithAggregatesInput = {
  AND?: Prisma.ImageLibraryScalarWhereWithAggregatesInput | Prisma.ImageLibraryScalarWhereWithAggregatesInput[]
  OR?: Prisma.ImageLibraryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ImageLibraryScalarWhereWithAggregatesInput | Prisma.ImageLibraryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ImageLibrary"> | string
  url?: Prisma.StringWithAggregatesFilter<"ImageLibrary"> | string
  type?: Prisma.EnumImageLibraryTypeWithAggregatesFilter<"ImageLibrary"> | $Enums.ImageLibraryType
  prompt?: Prisma.StringNullableWithAggregatesFilter<"ImageLibrary"> | string | null
  provider?: Prisma.StringNullableWithAggregatesFilter<"ImageLibrary"> | string | null
  modelId?: Prisma.StringNullableWithAggregatesFilter<"ImageLibrary"> | string | null
  userId?: Prisma.StringWithAggregatesFilter<"ImageLibrary"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ImageLibrary"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ImageLibrary"> | Date | string
}

export type ImageLibraryCreateInput = {
  id?: string
  url: string
  type: $Enums.ImageLibraryType
  prompt?: string | null
  provider?: string | null
  modelId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutImageLibraryInput
}

export type ImageLibraryUncheckedCreateInput = {
  id?: string
  url: string
  type: $Enums.ImageLibraryType
  prompt?: string | null
  provider?: string | null
  modelId?: string | null
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ImageLibraryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumImageLibraryTypeFieldUpdateOperationsInput | $Enums.ImageLibraryType
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutImageLibraryNestedInput
}

export type ImageLibraryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumImageLibraryTypeFieldUpdateOperationsInput | $Enums.ImageLibraryType
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ImageLibraryCreateManyInput = {
  id?: string
  url: string
  type: $Enums.ImageLibraryType
  prompt?: string | null
  provider?: string | null
  modelId?: string | null
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ImageLibraryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumImageLibraryTypeFieldUpdateOperationsInput | $Enums.ImageLibraryType
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ImageLibraryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumImageLibraryTypeFieldUpdateOperationsInput | $Enums.ImageLibraryType
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ImageLibraryListRelationFilter = {
  every?: Prisma.ImageLibraryWhereInput
  some?: Prisma.ImageLibraryWhereInput
  none?: Prisma.ImageLibraryWhereInput
}

export type ImageLibraryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ImageLibraryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  type?: Prisma.SortOrder
  prompt?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  modelId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ImageLibraryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  type?: Prisma.SortOrder
  prompt?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  modelId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ImageLibraryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  type?: Prisma.SortOrder
  prompt?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  modelId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ImageLibraryCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ImageLibraryCreateWithoutUserInput, Prisma.ImageLibraryUncheckedCreateWithoutUserInput> | Prisma.ImageLibraryCreateWithoutUserInput[] | Prisma.ImageLibraryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ImageLibraryCreateOrConnectWithoutUserInput | Prisma.ImageLibraryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ImageLibraryCreateManyUserInputEnvelope
  connect?: Prisma.ImageLibraryWhereUniqueInput | Prisma.ImageLibraryWhereUniqueInput[]
}

export type ImageLibraryUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ImageLibraryCreateWithoutUserInput, Prisma.ImageLibraryUncheckedCreateWithoutUserInput> | Prisma.ImageLibraryCreateWithoutUserInput[] | Prisma.ImageLibraryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ImageLibraryCreateOrConnectWithoutUserInput | Prisma.ImageLibraryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ImageLibraryCreateManyUserInputEnvelope
  connect?: Prisma.ImageLibraryWhereUniqueInput | Prisma.ImageLibraryWhereUniqueInput[]
}

export type ImageLibraryUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ImageLibraryCreateWithoutUserInput, Prisma.ImageLibraryUncheckedCreateWithoutUserInput> | Prisma.ImageLibraryCreateWithoutUserInput[] | Prisma.ImageLibraryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ImageLibraryCreateOrConnectWithoutUserInput | Prisma.ImageLibraryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ImageLibraryUpsertWithWhereUniqueWithoutUserInput | Prisma.ImageLibraryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ImageLibraryCreateManyUserInputEnvelope
  set?: Prisma.ImageLibraryWhereUniqueInput | Prisma.ImageLibraryWhereUniqueInput[]
  disconnect?: Prisma.ImageLibraryWhereUniqueInput | Prisma.ImageLibraryWhereUniqueInput[]
  delete?: Prisma.ImageLibraryWhereUniqueInput | Prisma.ImageLibraryWhereUniqueInput[]
  connect?: Prisma.ImageLibraryWhereUniqueInput | Prisma.ImageLibraryWhereUniqueInput[]
  update?: Prisma.ImageLibraryUpdateWithWhereUniqueWithoutUserInput | Prisma.ImageLibraryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ImageLibraryUpdateManyWithWhereWithoutUserInput | Prisma.ImageLibraryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ImageLibraryScalarWhereInput | Prisma.ImageLibraryScalarWhereInput[]
}

export type ImageLibraryUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ImageLibraryCreateWithoutUserInput, Prisma.ImageLibraryUncheckedCreateWithoutUserInput> | Prisma.ImageLibraryCreateWithoutUserInput[] | Prisma.ImageLibraryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ImageLibraryCreateOrConnectWithoutUserInput | Prisma.ImageLibraryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ImageLibraryUpsertWithWhereUniqueWithoutUserInput | Prisma.ImageLibraryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ImageLibraryCreateManyUserInputEnvelope
  set?: Prisma.ImageLibraryWhereUniqueInput | Prisma.ImageLibraryWhereUniqueInput[]
  disconnect?: Prisma.ImageLibraryWhereUniqueInput | Prisma.ImageLibraryWhereUniqueInput[]
  delete?: Prisma.ImageLibraryWhereUniqueInput | Prisma.ImageLibraryWhereUniqueInput[]
  connect?: Prisma.ImageLibraryWhereUniqueInput | Prisma.ImageLibraryWhereUniqueInput[]
  update?: Prisma.ImageLibraryUpdateWithWhereUniqueWithoutUserInput | Prisma.ImageLibraryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ImageLibraryUpdateManyWithWhereWithoutUserInput | Prisma.ImageLibraryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ImageLibraryScalarWhereInput | Prisma.ImageLibraryScalarWhereInput[]
}

export type EnumImageLibraryTypeFieldUpdateOperationsInput = {
  set?: $Enums.ImageLibraryType
}

export type ImageLibraryCreateWithoutUserInput = {
  id?: string
  url: string
  type: $Enums.ImageLibraryType
  prompt?: string | null
  provider?: string | null
  modelId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ImageLibraryUncheckedCreateWithoutUserInput = {
  id?: string
  url: string
  type: $Enums.ImageLibraryType
  prompt?: string | null
  provider?: string | null
  modelId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ImageLibraryCreateOrConnectWithoutUserInput = {
  where: Prisma.ImageLibraryWhereUniqueInput
  create: Prisma.XOR<Prisma.ImageLibraryCreateWithoutUserInput, Prisma.ImageLibraryUncheckedCreateWithoutUserInput>
}

export type ImageLibraryCreateManyUserInputEnvelope = {
  data: Prisma.ImageLibraryCreateManyUserInput | Prisma.ImageLibraryCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ImageLibraryUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ImageLibraryWhereUniqueInput
  update: Prisma.XOR<Prisma.ImageLibraryUpdateWithoutUserInput, Prisma.ImageLibraryUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ImageLibraryCreateWithoutUserInput, Prisma.ImageLibraryUncheckedCreateWithoutUserInput>
}

export type ImageLibraryUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ImageLibraryWhereUniqueInput
  data: Prisma.XOR<Prisma.ImageLibraryUpdateWithoutUserInput, Prisma.ImageLibraryUncheckedUpdateWithoutUserInput>
}

export type ImageLibraryUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ImageLibraryScalarWhereInput
  data: Prisma.XOR<Prisma.ImageLibraryUpdateManyMutationInput, Prisma.ImageLibraryUncheckedUpdateManyWithoutUserInput>
}

export type ImageLibraryScalarWhereInput = {
  AND?: Prisma.ImageLibraryScalarWhereInput | Prisma.ImageLibraryScalarWhereInput[]
  OR?: Prisma.ImageLibraryScalarWhereInput[]
  NOT?: Prisma.ImageLibraryScalarWhereInput | Prisma.ImageLibraryScalarWhereInput[]
  id?: Prisma.StringFilter<"ImageLibrary"> | string
  url?: Prisma.StringFilter<"ImageLibrary"> | string
  type?: Prisma.EnumImageLibraryTypeFilter<"ImageLibrary"> | $Enums.ImageLibraryType
  prompt?: Prisma.StringNullableFilter<"ImageLibrary"> | string | null
  provider?: Prisma.StringNullableFilter<"ImageLibrary"> | string | null
  modelId?: Prisma.StringNullableFilter<"ImageLibrary"> | string | null
  userId?: Prisma.StringFilter<"ImageLibrary"> | string
  createdAt?: Prisma.DateTimeFilter<"ImageLibrary"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ImageLibrary"> | Date | string
}

export type ImageLibraryCreateManyUserInput = {
  id?: string
  url: string
  type: $Enums.ImageLibraryType
  prompt?: string | null
  provider?: string | null
  modelId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ImageLibraryUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumImageLibraryTypeFieldUpdateOperationsInput | $Enums.ImageLibraryType
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ImageLibraryUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumImageLibraryTypeFieldUpdateOperationsInput | $Enums.ImageLibraryType
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ImageLibraryUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumImageLibraryTypeFieldUpdateOperationsInput | $Enums.ImageLibraryType
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ImageLibrarySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  type?: boolean
  prompt?: boolean
  provider?: boolean
  modelId?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["imageLibrary"]>

export type ImageLibrarySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  type?: boolean
  prompt?: boolean
  provider?: boolean
  modelId?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["imageLibrary"]>

export type ImageLibrarySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  type?: boolean
  prompt?: boolean
  provider?: boolean
  modelId?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["imageLibrary"]>

export type ImageLibrarySelectScalar = {
  id?: boolean
  url?: boolean
  type?: boolean
  prompt?: boolean
  provider?: boolean
  modelId?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ImageLibraryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "url" | "type" | "prompt" | "provider" | "modelId" | "userId" | "createdAt" | "updatedAt", ExtArgs["result"]["imageLibrary"]>
export type ImageLibraryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ImageLibraryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ImageLibraryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ImageLibraryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ImageLibrary"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    url: string
    type: $Enums.ImageLibraryType
    prompt: string | null
    provider: string | null
    modelId: string | null
    userId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["imageLibrary"]>
  composites: {}
}

export type ImageLibraryGetPayload<S extends boolean | null | undefined | ImageLibraryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ImageLibraryPayload, S>

export type ImageLibraryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ImageLibraryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ImageLibraryCountAggregateInputType | true
  }

export interface ImageLibraryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ImageLibrary'], meta: { name: 'ImageLibrary' } }
  /**
   * Find zero or one ImageLibrary that matches the filter.
   * @param {ImageLibraryFindUniqueArgs} args - Arguments to find a ImageLibrary
   * @example
   * // Get one ImageLibrary
   * const imageLibrary = await prisma.imageLibrary.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ImageLibraryFindUniqueArgs>(args: Prisma.SelectSubset<T, ImageLibraryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ImageLibraryClient<runtime.Types.Result.GetResult<Prisma.$ImageLibraryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ImageLibrary that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ImageLibraryFindUniqueOrThrowArgs} args - Arguments to find a ImageLibrary
   * @example
   * // Get one ImageLibrary
   * const imageLibrary = await prisma.imageLibrary.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ImageLibraryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ImageLibraryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ImageLibraryClient<runtime.Types.Result.GetResult<Prisma.$ImageLibraryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ImageLibrary that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImageLibraryFindFirstArgs} args - Arguments to find a ImageLibrary
   * @example
   * // Get one ImageLibrary
   * const imageLibrary = await prisma.imageLibrary.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ImageLibraryFindFirstArgs>(args?: Prisma.SelectSubset<T, ImageLibraryFindFirstArgs<ExtArgs>>): Prisma.Prisma__ImageLibraryClient<runtime.Types.Result.GetResult<Prisma.$ImageLibraryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ImageLibrary that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImageLibraryFindFirstOrThrowArgs} args - Arguments to find a ImageLibrary
   * @example
   * // Get one ImageLibrary
   * const imageLibrary = await prisma.imageLibrary.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ImageLibraryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ImageLibraryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ImageLibraryClient<runtime.Types.Result.GetResult<Prisma.$ImageLibraryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ImageLibraries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImageLibraryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ImageLibraries
   * const imageLibraries = await prisma.imageLibrary.findMany()
   * 
   * // Get first 10 ImageLibraries
   * const imageLibraries = await prisma.imageLibrary.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const imageLibraryWithIdOnly = await prisma.imageLibrary.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ImageLibraryFindManyArgs>(args?: Prisma.SelectSubset<T, ImageLibraryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImageLibraryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ImageLibrary.
   * @param {ImageLibraryCreateArgs} args - Arguments to create a ImageLibrary.
   * @example
   * // Create one ImageLibrary
   * const ImageLibrary = await prisma.imageLibrary.create({
   *   data: {
   *     // ... data to create a ImageLibrary
   *   }
   * })
   * 
   */
  create<T extends ImageLibraryCreateArgs>(args: Prisma.SelectSubset<T, ImageLibraryCreateArgs<ExtArgs>>): Prisma.Prisma__ImageLibraryClient<runtime.Types.Result.GetResult<Prisma.$ImageLibraryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ImageLibraries.
   * @param {ImageLibraryCreateManyArgs} args - Arguments to create many ImageLibraries.
   * @example
   * // Create many ImageLibraries
   * const imageLibrary = await prisma.imageLibrary.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ImageLibraryCreateManyArgs>(args?: Prisma.SelectSubset<T, ImageLibraryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ImageLibraries and returns the data saved in the database.
   * @param {ImageLibraryCreateManyAndReturnArgs} args - Arguments to create many ImageLibraries.
   * @example
   * // Create many ImageLibraries
   * const imageLibrary = await prisma.imageLibrary.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ImageLibraries and only return the `id`
   * const imageLibraryWithIdOnly = await prisma.imageLibrary.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ImageLibraryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ImageLibraryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImageLibraryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ImageLibrary.
   * @param {ImageLibraryDeleteArgs} args - Arguments to delete one ImageLibrary.
   * @example
   * // Delete one ImageLibrary
   * const ImageLibrary = await prisma.imageLibrary.delete({
   *   where: {
   *     // ... filter to delete one ImageLibrary
   *   }
   * })
   * 
   */
  delete<T extends ImageLibraryDeleteArgs>(args: Prisma.SelectSubset<T, ImageLibraryDeleteArgs<ExtArgs>>): Prisma.Prisma__ImageLibraryClient<runtime.Types.Result.GetResult<Prisma.$ImageLibraryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ImageLibrary.
   * @param {ImageLibraryUpdateArgs} args - Arguments to update one ImageLibrary.
   * @example
   * // Update one ImageLibrary
   * const imageLibrary = await prisma.imageLibrary.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ImageLibraryUpdateArgs>(args: Prisma.SelectSubset<T, ImageLibraryUpdateArgs<ExtArgs>>): Prisma.Prisma__ImageLibraryClient<runtime.Types.Result.GetResult<Prisma.$ImageLibraryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ImageLibraries.
   * @param {ImageLibraryDeleteManyArgs} args - Arguments to filter ImageLibraries to delete.
   * @example
   * // Delete a few ImageLibraries
   * const { count } = await prisma.imageLibrary.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ImageLibraryDeleteManyArgs>(args?: Prisma.SelectSubset<T, ImageLibraryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ImageLibraries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImageLibraryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ImageLibraries
   * const imageLibrary = await prisma.imageLibrary.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ImageLibraryUpdateManyArgs>(args: Prisma.SelectSubset<T, ImageLibraryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ImageLibraries and returns the data updated in the database.
   * @param {ImageLibraryUpdateManyAndReturnArgs} args - Arguments to update many ImageLibraries.
   * @example
   * // Update many ImageLibraries
   * const imageLibrary = await prisma.imageLibrary.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ImageLibraries and only return the `id`
   * const imageLibraryWithIdOnly = await prisma.imageLibrary.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ImageLibraryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ImageLibraryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImageLibraryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ImageLibrary.
   * @param {ImageLibraryUpsertArgs} args - Arguments to update or create a ImageLibrary.
   * @example
   * // Update or create a ImageLibrary
   * const imageLibrary = await prisma.imageLibrary.upsert({
   *   create: {
   *     // ... data to create a ImageLibrary
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ImageLibrary we want to update
   *   }
   * })
   */
  upsert<T extends ImageLibraryUpsertArgs>(args: Prisma.SelectSubset<T, ImageLibraryUpsertArgs<ExtArgs>>): Prisma.Prisma__ImageLibraryClient<runtime.Types.Result.GetResult<Prisma.$ImageLibraryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ImageLibraries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImageLibraryCountArgs} args - Arguments to filter ImageLibraries to count.
   * @example
   * // Count the number of ImageLibraries
   * const count = await prisma.imageLibrary.count({
   *   where: {
   *     // ... the filter for the ImageLibraries we want to count
   *   }
   * })
  **/
  count<T extends ImageLibraryCountArgs>(
    args?: Prisma.Subset<T, ImageLibraryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ImageLibraryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ImageLibrary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImageLibraryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ImageLibraryAggregateArgs>(args: Prisma.Subset<T, ImageLibraryAggregateArgs>): Prisma.PrismaPromise<GetImageLibraryAggregateType<T>>

  /**
   * Group by ImageLibrary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImageLibraryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ImageLibraryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ImageLibraryGroupByArgs['orderBy'] }
      : { orderBy?: ImageLibraryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ImageLibraryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetImageLibraryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ImageLibrary model
 */
readonly fields: ImageLibraryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ImageLibrary.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ImageLibraryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ImageLibrary model
 */
export interface ImageLibraryFieldRefs {
  readonly id: Prisma.FieldRef<"ImageLibrary", 'String'>
  readonly url: Prisma.FieldRef<"ImageLibrary", 'String'>
  readonly type: Prisma.FieldRef<"ImageLibrary", 'ImageLibraryType'>
  readonly prompt: Prisma.FieldRef<"ImageLibrary", 'String'>
  readonly provider: Prisma.FieldRef<"ImageLibrary", 'String'>
  readonly modelId: Prisma.FieldRef<"ImageLibrary", 'String'>
  readonly userId: Prisma.FieldRef<"ImageLibrary", 'String'>
  readonly createdAt: Prisma.FieldRef<"ImageLibrary", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ImageLibrary", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ImageLibrary findUnique
 */
export type ImageLibraryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImageLibrary
   */
  select?: Prisma.ImageLibrarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImageLibrary
   */
  omit?: Prisma.ImageLibraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageLibraryInclude<ExtArgs> | null
  /**
   * Filter, which ImageLibrary to fetch.
   */
  where: Prisma.ImageLibraryWhereUniqueInput
}

/**
 * ImageLibrary findUniqueOrThrow
 */
export type ImageLibraryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImageLibrary
   */
  select?: Prisma.ImageLibrarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImageLibrary
   */
  omit?: Prisma.ImageLibraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageLibraryInclude<ExtArgs> | null
  /**
   * Filter, which ImageLibrary to fetch.
   */
  where: Prisma.ImageLibraryWhereUniqueInput
}

/**
 * ImageLibrary findFirst
 */
export type ImageLibraryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImageLibrary
   */
  select?: Prisma.ImageLibrarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImageLibrary
   */
  omit?: Prisma.ImageLibraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageLibraryInclude<ExtArgs> | null
  /**
   * Filter, which ImageLibrary to fetch.
   */
  where?: Prisma.ImageLibraryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ImageLibraries to fetch.
   */
  orderBy?: Prisma.ImageLibraryOrderByWithRelationInput | Prisma.ImageLibraryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ImageLibraries.
   */
  cursor?: Prisma.ImageLibraryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ImageLibraries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ImageLibraries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ImageLibraries.
   */
  distinct?: Prisma.ImageLibraryScalarFieldEnum | Prisma.ImageLibraryScalarFieldEnum[]
}

/**
 * ImageLibrary findFirstOrThrow
 */
export type ImageLibraryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImageLibrary
   */
  select?: Prisma.ImageLibrarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImageLibrary
   */
  omit?: Prisma.ImageLibraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageLibraryInclude<ExtArgs> | null
  /**
   * Filter, which ImageLibrary to fetch.
   */
  where?: Prisma.ImageLibraryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ImageLibraries to fetch.
   */
  orderBy?: Prisma.ImageLibraryOrderByWithRelationInput | Prisma.ImageLibraryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ImageLibraries.
   */
  cursor?: Prisma.ImageLibraryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ImageLibraries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ImageLibraries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ImageLibraries.
   */
  distinct?: Prisma.ImageLibraryScalarFieldEnum | Prisma.ImageLibraryScalarFieldEnum[]
}

/**
 * ImageLibrary findMany
 */
export type ImageLibraryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImageLibrary
   */
  select?: Prisma.ImageLibrarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImageLibrary
   */
  omit?: Prisma.ImageLibraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageLibraryInclude<ExtArgs> | null
  /**
   * Filter, which ImageLibraries to fetch.
   */
  where?: Prisma.ImageLibraryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ImageLibraries to fetch.
   */
  orderBy?: Prisma.ImageLibraryOrderByWithRelationInput | Prisma.ImageLibraryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ImageLibraries.
   */
  cursor?: Prisma.ImageLibraryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ImageLibraries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ImageLibraries.
   */
  skip?: number
  distinct?: Prisma.ImageLibraryScalarFieldEnum | Prisma.ImageLibraryScalarFieldEnum[]
}

/**
 * ImageLibrary create
 */
export type ImageLibraryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImageLibrary
   */
  select?: Prisma.ImageLibrarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImageLibrary
   */
  omit?: Prisma.ImageLibraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageLibraryInclude<ExtArgs> | null
  /**
   * The data needed to create a ImageLibrary.
   */
  data: Prisma.XOR<Prisma.ImageLibraryCreateInput, Prisma.ImageLibraryUncheckedCreateInput>
}

/**
 * ImageLibrary createMany
 */
export type ImageLibraryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ImageLibraries.
   */
  data: Prisma.ImageLibraryCreateManyInput | Prisma.ImageLibraryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ImageLibrary createManyAndReturn
 */
export type ImageLibraryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImageLibrary
   */
  select?: Prisma.ImageLibrarySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ImageLibrary
   */
  omit?: Prisma.ImageLibraryOmit<ExtArgs> | null
  /**
   * The data used to create many ImageLibraries.
   */
  data: Prisma.ImageLibraryCreateManyInput | Prisma.ImageLibraryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageLibraryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ImageLibrary update
 */
export type ImageLibraryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImageLibrary
   */
  select?: Prisma.ImageLibrarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImageLibrary
   */
  omit?: Prisma.ImageLibraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageLibraryInclude<ExtArgs> | null
  /**
   * The data needed to update a ImageLibrary.
   */
  data: Prisma.XOR<Prisma.ImageLibraryUpdateInput, Prisma.ImageLibraryUncheckedUpdateInput>
  /**
   * Choose, which ImageLibrary to update.
   */
  where: Prisma.ImageLibraryWhereUniqueInput
}

/**
 * ImageLibrary updateMany
 */
export type ImageLibraryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ImageLibraries.
   */
  data: Prisma.XOR<Prisma.ImageLibraryUpdateManyMutationInput, Prisma.ImageLibraryUncheckedUpdateManyInput>
  /**
   * Filter which ImageLibraries to update
   */
  where?: Prisma.ImageLibraryWhereInput
  /**
   * Limit how many ImageLibraries to update.
   */
  limit?: number
}

/**
 * ImageLibrary updateManyAndReturn
 */
export type ImageLibraryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImageLibrary
   */
  select?: Prisma.ImageLibrarySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ImageLibrary
   */
  omit?: Prisma.ImageLibraryOmit<ExtArgs> | null
  /**
   * The data used to update ImageLibraries.
   */
  data: Prisma.XOR<Prisma.ImageLibraryUpdateManyMutationInput, Prisma.ImageLibraryUncheckedUpdateManyInput>
  /**
   * Filter which ImageLibraries to update
   */
  where?: Prisma.ImageLibraryWhereInput
  /**
   * Limit how many ImageLibraries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageLibraryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ImageLibrary upsert
 */
export type ImageLibraryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImageLibrary
   */
  select?: Prisma.ImageLibrarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImageLibrary
   */
  omit?: Prisma.ImageLibraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageLibraryInclude<ExtArgs> | null
  /**
   * The filter to search for the ImageLibrary to update in case it exists.
   */
  where: Prisma.ImageLibraryWhereUniqueInput
  /**
   * In case the ImageLibrary found by the `where` argument doesn't exist, create a new ImageLibrary with this data.
   */
  create: Prisma.XOR<Prisma.ImageLibraryCreateInput, Prisma.ImageLibraryUncheckedCreateInput>
  /**
   * In case the ImageLibrary was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ImageLibraryUpdateInput, Prisma.ImageLibraryUncheckedUpdateInput>
}

/**
 * ImageLibrary delete
 */
export type ImageLibraryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImageLibrary
   */
  select?: Prisma.ImageLibrarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImageLibrary
   */
  omit?: Prisma.ImageLibraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageLibraryInclude<ExtArgs> | null
  /**
   * Filter which ImageLibrary to delete.
   */
  where: Prisma.ImageLibraryWhereUniqueInput
}

/**
 * ImageLibrary deleteMany
 */
export type ImageLibraryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ImageLibraries to delete
   */
  where?: Prisma.ImageLibraryWhereInput
  /**
   * Limit how many ImageLibraries to delete.
   */
  limit?: number
}

/**
 * ImageLibrary without action
 */
export type ImageLibraryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImageLibrary
   */
  select?: Prisma.ImageLibrarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImageLibrary
   */
  omit?: Prisma.ImageLibraryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImageLibraryInclude<ExtArgs> | null
}
