
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Presentation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Presentation
 * 
 */
export type PresentationModel = runtime.Types.Result.DefaultSelection<Prisma.$PresentationPayload>

export type AggregatePresentation = {
  _count: PresentationCountAggregateOutputType | null
  _avg: PresentationAvgAggregateOutputType | null
  _sum: PresentationSumAggregateOutputType | null
  _min: PresentationMinAggregateOutputType | null
  _max: PresentationMaxAggregateOutputType | null
}

export type PresentationAvgAggregateOutputType = {
  numSlides: number | null
}

export type PresentationSumAggregateOutputType = {
  numSlides: number | null
}

export type PresentationMinAggregateOutputType = {
  id: string | null
  content: string | null
  imageSource: string | null
  imageProvider: string | null
  imageModelId: string | null
  prompt: string | null
  modelProvider: string | null
  modelId: string | null
  pageStyle: string | null
  numSlides: number | null
  tone: string | null
  language: string | null
  templateId: string | null
  themeId: string | null
  status: $Enums.PresentationStatus | null
}

export type PresentationMaxAggregateOutputType = {
  id: string | null
  content: string | null
  imageSource: string | null
  imageProvider: string | null
  imageModelId: string | null
  prompt: string | null
  modelProvider: string | null
  modelId: string | null
  pageStyle: string | null
  numSlides: number | null
  tone: string | null
  language: string | null
  templateId: string | null
  themeId: string | null
  status: $Enums.PresentationStatus | null
}

export type PresentationCountAggregateOutputType = {
  id: number
  content: number
  imageSource: number
  imageProvider: number
  imageModelId: number
  prompt: number
  modelProvider: number
  modelId: number
  pageStyle: number
  numSlides: number
  tone: number
  language: number
  outline: number
  searchResults: number
  templateId: number
  themeId: number
  status: number
  _all: number
}


export type PresentationAvgAggregateInputType = {
  numSlides?: true
}

export type PresentationSumAggregateInputType = {
  numSlides?: true
}

export type PresentationMinAggregateInputType = {
  id?: true
  content?: true
  imageSource?: true
  imageProvider?: true
  imageModelId?: true
  prompt?: true
  modelProvider?: true
  modelId?: true
  pageStyle?: true
  numSlides?: true
  tone?: true
  language?: true
  templateId?: true
  themeId?: true
  status?: true
}

export type PresentationMaxAggregateInputType = {
  id?: true
  content?: true
  imageSource?: true
  imageProvider?: true
  imageModelId?: true
  prompt?: true
  modelProvider?: true
  modelId?: true
  pageStyle?: true
  numSlides?: true
  tone?: true
  language?: true
  templateId?: true
  themeId?: true
  status?: true
}

export type PresentationCountAggregateInputType = {
  id?: true
  content?: true
  imageSource?: true
  imageProvider?: true
  imageModelId?: true
  prompt?: true
  modelProvider?: true
  modelId?: true
  pageStyle?: true
  numSlides?: true
  tone?: true
  language?: true
  outline?: true
  searchResults?: true
  templateId?: true
  themeId?: true
  status?: true
  _all?: true
}

export type PresentationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Presentation to aggregate.
   */
  where?: Prisma.PresentationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Presentations to fetch.
   */
  orderBy?: Prisma.PresentationOrderByWithRelationInput | Prisma.PresentationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PresentationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Presentations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Presentations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Presentations
  **/
  _count?: true | PresentationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PresentationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PresentationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PresentationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PresentationMaxAggregateInputType
}

export type GetPresentationAggregateType<T extends PresentationAggregateArgs> = {
      [P in keyof T & keyof AggregatePresentation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePresentation[P]>
    : Prisma.GetScalarType<T[P], AggregatePresentation[P]>
}




export type PresentationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PresentationWhereInput
  orderBy?: Prisma.PresentationOrderByWithAggregationInput | Prisma.PresentationOrderByWithAggregationInput[]
  by: Prisma.PresentationScalarFieldEnum[] | Prisma.PresentationScalarFieldEnum
  having?: Prisma.PresentationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PresentationCountAggregateInputType | true
  _avg?: PresentationAvgAggregateInputType
  _sum?: PresentationSumAggregateInputType
  _min?: PresentationMinAggregateInputType
  _max?: PresentationMaxAggregateInputType
}

export type PresentationGroupByOutputType = {
  id: string
  content: string
  imageSource: string
  imageProvider: string | null
  imageModelId: string | null
  prompt: string | null
  modelProvider: string | null
  modelId: string | null
  pageStyle: string | null
  numSlides: number | null
  tone: string | null
  language: string | null
  outline: string[]
  searchResults: runtime.JsonValue | null
  templateId: string | null
  themeId: string
  status: $Enums.PresentationStatus
  _count: PresentationCountAggregateOutputType | null
  _avg: PresentationAvgAggregateOutputType | null
  _sum: PresentationSumAggregateOutputType | null
  _min: PresentationMinAggregateOutputType | null
  _max: PresentationMaxAggregateOutputType | null
}

type GetPresentationGroupByPayload<T extends PresentationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PresentationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PresentationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PresentationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PresentationGroupByOutputType[P]>
      }
    >
  >



export type PresentationWhereInput = {
  AND?: Prisma.PresentationWhereInput | Prisma.PresentationWhereInput[]
  OR?: Prisma.PresentationWhereInput[]
  NOT?: Prisma.PresentationWhereInput | Prisma.PresentationWhereInput[]
  id?: Prisma.StringFilter<"Presentation"> | string
  content?: Prisma.StringFilter<"Presentation"> | string
  imageSource?: Prisma.StringFilter<"Presentation"> | string
  imageProvider?: Prisma.StringNullableFilter<"Presentation"> | string | null
  imageModelId?: Prisma.StringNullableFilter<"Presentation"> | string | null
  prompt?: Prisma.StringNullableFilter<"Presentation"> | string | null
  modelProvider?: Prisma.StringNullableFilter<"Presentation"> | string | null
  modelId?: Prisma.StringNullableFilter<"Presentation"> | string | null
  pageStyle?: Prisma.StringNullableFilter<"Presentation"> | string | null
  numSlides?: Prisma.IntNullableFilter<"Presentation"> | number | null
  tone?: Prisma.StringNullableFilter<"Presentation"> | string | null
  language?: Prisma.StringNullableFilter<"Presentation"> | string | null
  outline?: Prisma.StringNullableListFilter<"Presentation">
  searchResults?: Prisma.JsonNullableFilter<"Presentation">
  templateId?: Prisma.StringNullableFilter<"Presentation"> | string | null
  themeId?: Prisma.StringFilter<"Presentation"> | string
  status?: Prisma.EnumPresentationStatusFilter<"Presentation"> | $Enums.PresentationStatus
  base?: Prisma.XOR<Prisma.BaseDocumentScalarRelationFilter, Prisma.BaseDocumentWhereInput>
  theme?: Prisma.XOR<Prisma.PresentationThemeNullableScalarRelationFilter, Prisma.PresentationThemeWhereInput> | null
}

export type PresentationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  imageSource?: Prisma.SortOrder
  imageProvider?: Prisma.SortOrderInput | Prisma.SortOrder
  imageModelId?: Prisma.SortOrderInput | Prisma.SortOrder
  prompt?: Prisma.SortOrderInput | Prisma.SortOrder
  modelProvider?: Prisma.SortOrderInput | Prisma.SortOrder
  modelId?: Prisma.SortOrderInput | Prisma.SortOrder
  pageStyle?: Prisma.SortOrderInput | Prisma.SortOrder
  numSlides?: Prisma.SortOrderInput | Prisma.SortOrder
  tone?: Prisma.SortOrderInput | Prisma.SortOrder
  language?: Prisma.SortOrderInput | Prisma.SortOrder
  outline?: Prisma.SortOrder
  searchResults?: Prisma.SortOrderInput | Prisma.SortOrder
  templateId?: Prisma.SortOrderInput | Prisma.SortOrder
  themeId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  base?: Prisma.BaseDocumentOrderByWithRelationInput
  theme?: Prisma.PresentationThemeOrderByWithRelationInput
}

export type PresentationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PresentationWhereInput | Prisma.PresentationWhereInput[]
  OR?: Prisma.PresentationWhereInput[]
  NOT?: Prisma.PresentationWhereInput | Prisma.PresentationWhereInput[]
  content?: Prisma.StringFilter<"Presentation"> | string
  imageSource?: Prisma.StringFilter<"Presentation"> | string
  imageProvider?: Prisma.StringNullableFilter<"Presentation"> | string | null
  imageModelId?: Prisma.StringNullableFilter<"Presentation"> | string | null
  prompt?: Prisma.StringNullableFilter<"Presentation"> | string | null
  modelProvider?: Prisma.StringNullableFilter<"Presentation"> | string | null
  modelId?: Prisma.StringNullableFilter<"Presentation"> | string | null
  pageStyle?: Prisma.StringNullableFilter<"Presentation"> | string | null
  numSlides?: Prisma.IntNullableFilter<"Presentation"> | number | null
  tone?: Prisma.StringNullableFilter<"Presentation"> | string | null
  language?: Prisma.StringNullableFilter<"Presentation"> | string | null
  outline?: Prisma.StringNullableListFilter<"Presentation">
  searchResults?: Prisma.JsonNullableFilter<"Presentation">
  templateId?: Prisma.StringNullableFilter<"Presentation"> | string | null
  themeId?: Prisma.StringFilter<"Presentation"> | string
  status?: Prisma.EnumPresentationStatusFilter<"Presentation"> | $Enums.PresentationStatus
  base?: Prisma.XOR<Prisma.BaseDocumentScalarRelationFilter, Prisma.BaseDocumentWhereInput>
  theme?: Prisma.XOR<Prisma.PresentationThemeNullableScalarRelationFilter, Prisma.PresentationThemeWhereInput> | null
}, "id">

export type PresentationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  imageSource?: Prisma.SortOrder
  imageProvider?: Prisma.SortOrderInput | Prisma.SortOrder
  imageModelId?: Prisma.SortOrderInput | Prisma.SortOrder
  prompt?: Prisma.SortOrderInput | Prisma.SortOrder
  modelProvider?: Prisma.SortOrderInput | Prisma.SortOrder
  modelId?: Prisma.SortOrderInput | Prisma.SortOrder
  pageStyle?: Prisma.SortOrderInput | Prisma.SortOrder
  numSlides?: Prisma.SortOrderInput | Prisma.SortOrder
  tone?: Prisma.SortOrderInput | Prisma.SortOrder
  language?: Prisma.SortOrderInput | Prisma.SortOrder
  outline?: Prisma.SortOrder
  searchResults?: Prisma.SortOrderInput | Prisma.SortOrder
  templateId?: Prisma.SortOrderInput | Prisma.SortOrder
  themeId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  _count?: Prisma.PresentationCountOrderByAggregateInput
  _avg?: Prisma.PresentationAvgOrderByAggregateInput
  _max?: Prisma.PresentationMaxOrderByAggregateInput
  _min?: Prisma.PresentationMinOrderByAggregateInput
  _sum?: Prisma.PresentationSumOrderByAggregateInput
}

export type PresentationScalarWhereWithAggregatesInput = {
  AND?: Prisma.PresentationScalarWhereWithAggregatesInput | Prisma.PresentationScalarWhereWithAggregatesInput[]
  OR?: Prisma.PresentationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PresentationScalarWhereWithAggregatesInput | Prisma.PresentationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Presentation"> | string
  content?: Prisma.StringWithAggregatesFilter<"Presentation"> | string
  imageSource?: Prisma.StringWithAggregatesFilter<"Presentation"> | string
  imageProvider?: Prisma.StringNullableWithAggregatesFilter<"Presentation"> | string | null
  imageModelId?: Prisma.StringNullableWithAggregatesFilter<"Presentation"> | string | null
  prompt?: Prisma.StringNullableWithAggregatesFilter<"Presentation"> | string | null
  modelProvider?: Prisma.StringNullableWithAggregatesFilter<"Presentation"> | string | null
  modelId?: Prisma.StringNullableWithAggregatesFilter<"Presentation"> | string | null
  pageStyle?: Prisma.StringNullableWithAggregatesFilter<"Presentation"> | string | null
  numSlides?: Prisma.IntNullableWithAggregatesFilter<"Presentation"> | number | null
  tone?: Prisma.StringNullableWithAggregatesFilter<"Presentation"> | string | null
  language?: Prisma.StringNullableWithAggregatesFilter<"Presentation"> | string | null
  outline?: Prisma.StringNullableListFilter<"Presentation">
  searchResults?: Prisma.JsonNullableWithAggregatesFilter<"Presentation">
  templateId?: Prisma.StringNullableWithAggregatesFilter<"Presentation"> | string | null
  themeId?: Prisma.StringWithAggregatesFilter<"Presentation"> | string
  status?: Prisma.EnumPresentationStatusWithAggregatesFilter<"Presentation"> | $Enums.PresentationStatus
}

export type PresentationCreateInput = {
  content: string
  imageSource?: string
  imageProvider?: string | null
  imageModelId?: string | null
  prompt?: string | null
  modelProvider?: string | null
  modelId?: string | null
  pageStyle?: string | null
  numSlides?: number | null
  tone?: string | null
  language?: string | null
  outline?: Prisma.PresentationCreateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: string | null
  status?: $Enums.PresentationStatus
  base?: Prisma.BaseDocumentCreateNestedOneWithoutPresentationInput
  theme?: Prisma.PresentationThemeCreateNestedOneWithoutPresentationsInput
}

export type PresentationUncheckedCreateInput = {
  id?: string
  content: string
  imageSource?: string
  imageProvider?: string | null
  imageModelId?: string | null
  prompt?: string | null
  modelProvider?: string | null
  modelId?: string | null
  pageStyle?: string | null
  numSlides?: number | null
  tone?: string | null
  language?: string | null
  outline?: Prisma.PresentationCreateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: string | null
  themeId: string
  status?: $Enums.PresentationStatus
}

export type PresentationUpdateInput = {
  content?: Prisma.StringFieldUpdateOperationsInput | string
  imageSource?: Prisma.StringFieldUpdateOperationsInput | string
  imageProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageModelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pageStyle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  numSlides?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outline?: Prisma.PresentationUpdateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumPresentationStatusFieldUpdateOperationsInput | $Enums.PresentationStatus
  base?: Prisma.BaseDocumentUpdateOneRequiredWithoutPresentationNestedInput
  theme?: Prisma.PresentationThemeUpdateOneWithoutPresentationsNestedInput
}

export type PresentationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  imageSource?: Prisma.StringFieldUpdateOperationsInput | string
  imageProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageModelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pageStyle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  numSlides?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outline?: Prisma.PresentationUpdateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPresentationStatusFieldUpdateOperationsInput | $Enums.PresentationStatus
}

export type PresentationCreateManyInput = {
  id?: string
  content: string
  imageSource?: string
  imageProvider?: string | null
  imageModelId?: string | null
  prompt?: string | null
  modelProvider?: string | null
  modelId?: string | null
  pageStyle?: string | null
  numSlides?: number | null
  tone?: string | null
  language?: string | null
  outline?: Prisma.PresentationCreateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: string | null
  themeId: string
  status?: $Enums.PresentationStatus
}

export type PresentationUpdateManyMutationInput = {
  content?: Prisma.StringFieldUpdateOperationsInput | string
  imageSource?: Prisma.StringFieldUpdateOperationsInput | string
  imageProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageModelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pageStyle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  numSlides?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outline?: Prisma.PresentationUpdateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumPresentationStatusFieldUpdateOperationsInput | $Enums.PresentationStatus
}

export type PresentationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  imageSource?: Prisma.StringFieldUpdateOperationsInput | string
  imageProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageModelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pageStyle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  numSlides?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outline?: Prisma.PresentationUpdateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPresentationStatusFieldUpdateOperationsInput | $Enums.PresentationStatus
}

export type PresentationNullableScalarRelationFilter = {
  is?: Prisma.PresentationWhereInput | null
  isNot?: Prisma.PresentationWhereInput | null
}

export type PresentationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  imageSource?: Prisma.SortOrder
  imageProvider?: Prisma.SortOrder
  imageModelId?: Prisma.SortOrder
  prompt?: Prisma.SortOrder
  modelProvider?: Prisma.SortOrder
  modelId?: Prisma.SortOrder
  pageStyle?: Prisma.SortOrder
  numSlides?: Prisma.SortOrder
  tone?: Prisma.SortOrder
  language?: Prisma.SortOrder
  outline?: Prisma.SortOrder
  searchResults?: Prisma.SortOrder
  templateId?: Prisma.SortOrder
  themeId?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type PresentationAvgOrderByAggregateInput = {
  numSlides?: Prisma.SortOrder
}

export type PresentationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  imageSource?: Prisma.SortOrder
  imageProvider?: Prisma.SortOrder
  imageModelId?: Prisma.SortOrder
  prompt?: Prisma.SortOrder
  modelProvider?: Prisma.SortOrder
  modelId?: Prisma.SortOrder
  pageStyle?: Prisma.SortOrder
  numSlides?: Prisma.SortOrder
  tone?: Prisma.SortOrder
  language?: Prisma.SortOrder
  templateId?: Prisma.SortOrder
  themeId?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type PresentationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  imageSource?: Prisma.SortOrder
  imageProvider?: Prisma.SortOrder
  imageModelId?: Prisma.SortOrder
  prompt?: Prisma.SortOrder
  modelProvider?: Prisma.SortOrder
  modelId?: Prisma.SortOrder
  pageStyle?: Prisma.SortOrder
  numSlides?: Prisma.SortOrder
  tone?: Prisma.SortOrder
  language?: Prisma.SortOrder
  templateId?: Prisma.SortOrder
  themeId?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type PresentationSumOrderByAggregateInput = {
  numSlides?: Prisma.SortOrder
}

export type PresentationListRelationFilter = {
  every?: Prisma.PresentationWhereInput
  some?: Prisma.PresentationWhereInput
  none?: Prisma.PresentationWhereInput
}

export type PresentationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PresentationCreateNestedOneWithoutBaseInput = {
  create?: Prisma.XOR<Prisma.PresentationCreateWithoutBaseInput, Prisma.PresentationUncheckedCreateWithoutBaseInput>
  connectOrCreate?: Prisma.PresentationCreateOrConnectWithoutBaseInput
  connect?: Prisma.PresentationWhereUniqueInput
}

export type PresentationUncheckedCreateNestedOneWithoutBaseInput = {
  create?: Prisma.XOR<Prisma.PresentationCreateWithoutBaseInput, Prisma.PresentationUncheckedCreateWithoutBaseInput>
  connectOrCreate?: Prisma.PresentationCreateOrConnectWithoutBaseInput
  connect?: Prisma.PresentationWhereUniqueInput
}

export type PresentationUpdateOneWithoutBaseNestedInput = {
  create?: Prisma.XOR<Prisma.PresentationCreateWithoutBaseInput, Prisma.PresentationUncheckedCreateWithoutBaseInput>
  connectOrCreate?: Prisma.PresentationCreateOrConnectWithoutBaseInput
  upsert?: Prisma.PresentationUpsertWithoutBaseInput
  disconnect?: Prisma.PresentationWhereInput | boolean
  delete?: Prisma.PresentationWhereInput | boolean
  connect?: Prisma.PresentationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PresentationUpdateToOneWithWhereWithoutBaseInput, Prisma.PresentationUpdateWithoutBaseInput>, Prisma.PresentationUncheckedUpdateWithoutBaseInput>
}

export type PresentationUncheckedUpdateOneWithoutBaseNestedInput = {
  create?: Prisma.XOR<Prisma.PresentationCreateWithoutBaseInput, Prisma.PresentationUncheckedCreateWithoutBaseInput>
  connectOrCreate?: Prisma.PresentationCreateOrConnectWithoutBaseInput
  upsert?: Prisma.PresentationUpsertWithoutBaseInput
  disconnect?: Prisma.PresentationWhereInput | boolean
  delete?: Prisma.PresentationWhereInput | boolean
  connect?: Prisma.PresentationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PresentationUpdateToOneWithWhereWithoutBaseInput, Prisma.PresentationUpdateWithoutBaseInput>, Prisma.PresentationUncheckedUpdateWithoutBaseInput>
}

export type PresentationCreateoutlineInput = {
  set: string[]
}

export type PresentationUpdateoutlineInput = {
  set?: string[]
  push?: string | string[]
}

export type EnumPresentationStatusFieldUpdateOperationsInput = {
  set?: $Enums.PresentationStatus
}

export type PresentationCreateNestedManyWithoutThemeInput = {
  create?: Prisma.XOR<Prisma.PresentationCreateWithoutThemeInput, Prisma.PresentationUncheckedCreateWithoutThemeInput> | Prisma.PresentationCreateWithoutThemeInput[] | Prisma.PresentationUncheckedCreateWithoutThemeInput[]
  connectOrCreate?: Prisma.PresentationCreateOrConnectWithoutThemeInput | Prisma.PresentationCreateOrConnectWithoutThemeInput[]
  createMany?: Prisma.PresentationCreateManyThemeInputEnvelope
  connect?: Prisma.PresentationWhereUniqueInput | Prisma.PresentationWhereUniqueInput[]
}

export type PresentationUncheckedCreateNestedManyWithoutThemeInput = {
  create?: Prisma.XOR<Prisma.PresentationCreateWithoutThemeInput, Prisma.PresentationUncheckedCreateWithoutThemeInput> | Prisma.PresentationCreateWithoutThemeInput[] | Prisma.PresentationUncheckedCreateWithoutThemeInput[]
  connectOrCreate?: Prisma.PresentationCreateOrConnectWithoutThemeInput | Prisma.PresentationCreateOrConnectWithoutThemeInput[]
  createMany?: Prisma.PresentationCreateManyThemeInputEnvelope
  connect?: Prisma.PresentationWhereUniqueInput | Prisma.PresentationWhereUniqueInput[]
}

export type PresentationUpdateManyWithoutThemeNestedInput = {
  create?: Prisma.XOR<Prisma.PresentationCreateWithoutThemeInput, Prisma.PresentationUncheckedCreateWithoutThemeInput> | Prisma.PresentationCreateWithoutThemeInput[] | Prisma.PresentationUncheckedCreateWithoutThemeInput[]
  connectOrCreate?: Prisma.PresentationCreateOrConnectWithoutThemeInput | Prisma.PresentationCreateOrConnectWithoutThemeInput[]
  upsert?: Prisma.PresentationUpsertWithWhereUniqueWithoutThemeInput | Prisma.PresentationUpsertWithWhereUniqueWithoutThemeInput[]
  createMany?: Prisma.PresentationCreateManyThemeInputEnvelope
  set?: Prisma.PresentationWhereUniqueInput | Prisma.PresentationWhereUniqueInput[]
  disconnect?: Prisma.PresentationWhereUniqueInput | Prisma.PresentationWhereUniqueInput[]
  delete?: Prisma.PresentationWhereUniqueInput | Prisma.PresentationWhereUniqueInput[]
  connect?: Prisma.PresentationWhereUniqueInput | Prisma.PresentationWhereUniqueInput[]
  update?: Prisma.PresentationUpdateWithWhereUniqueWithoutThemeInput | Prisma.PresentationUpdateWithWhereUniqueWithoutThemeInput[]
  updateMany?: Prisma.PresentationUpdateManyWithWhereWithoutThemeInput | Prisma.PresentationUpdateManyWithWhereWithoutThemeInput[]
  deleteMany?: Prisma.PresentationScalarWhereInput | Prisma.PresentationScalarWhereInput[]
}

export type PresentationUncheckedUpdateManyWithoutThemeNestedInput = {
  create?: Prisma.XOR<Prisma.PresentationCreateWithoutThemeInput, Prisma.PresentationUncheckedCreateWithoutThemeInput> | Prisma.PresentationCreateWithoutThemeInput[] | Prisma.PresentationUncheckedCreateWithoutThemeInput[]
  connectOrCreate?: Prisma.PresentationCreateOrConnectWithoutThemeInput | Prisma.PresentationCreateOrConnectWithoutThemeInput[]
  upsert?: Prisma.PresentationUpsertWithWhereUniqueWithoutThemeInput | Prisma.PresentationUpsertWithWhereUniqueWithoutThemeInput[]
  createMany?: Prisma.PresentationCreateManyThemeInputEnvelope
  set?: Prisma.PresentationWhereUniqueInput | Prisma.PresentationWhereUniqueInput[]
  disconnect?: Prisma.PresentationWhereUniqueInput | Prisma.PresentationWhereUniqueInput[]
  delete?: Prisma.PresentationWhereUniqueInput | Prisma.PresentationWhereUniqueInput[]
  connect?: Prisma.PresentationWhereUniqueInput | Prisma.PresentationWhereUniqueInput[]
  update?: Prisma.PresentationUpdateWithWhereUniqueWithoutThemeInput | Prisma.PresentationUpdateWithWhereUniqueWithoutThemeInput[]
  updateMany?: Prisma.PresentationUpdateManyWithWhereWithoutThemeInput | Prisma.PresentationUpdateManyWithWhereWithoutThemeInput[]
  deleteMany?: Prisma.PresentationScalarWhereInput | Prisma.PresentationScalarWhereInput[]
}

export type PresentationCreateWithoutBaseInput = {
  content: string
  imageSource?: string
  imageProvider?: string | null
  imageModelId?: string | null
  prompt?: string | null
  modelProvider?: string | null
  modelId?: string | null
  pageStyle?: string | null
  numSlides?: number | null
  tone?: string | null
  language?: string | null
  outline?: Prisma.PresentationCreateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: string | null
  status?: $Enums.PresentationStatus
  theme?: Prisma.PresentationThemeCreateNestedOneWithoutPresentationsInput
}

export type PresentationUncheckedCreateWithoutBaseInput = {
  content: string
  imageSource?: string
  imageProvider?: string | null
  imageModelId?: string | null
  prompt?: string | null
  modelProvider?: string | null
  modelId?: string | null
  pageStyle?: string | null
  numSlides?: number | null
  tone?: string | null
  language?: string | null
  outline?: Prisma.PresentationCreateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: string | null
  themeId: string
  status?: $Enums.PresentationStatus
}

export type PresentationCreateOrConnectWithoutBaseInput = {
  where: Prisma.PresentationWhereUniqueInput
  create: Prisma.XOR<Prisma.PresentationCreateWithoutBaseInput, Prisma.PresentationUncheckedCreateWithoutBaseInput>
}

export type PresentationUpsertWithoutBaseInput = {
  update: Prisma.XOR<Prisma.PresentationUpdateWithoutBaseInput, Prisma.PresentationUncheckedUpdateWithoutBaseInput>
  create: Prisma.XOR<Prisma.PresentationCreateWithoutBaseInput, Prisma.PresentationUncheckedCreateWithoutBaseInput>
  where?: Prisma.PresentationWhereInput
}

export type PresentationUpdateToOneWithWhereWithoutBaseInput = {
  where?: Prisma.PresentationWhereInput
  data: Prisma.XOR<Prisma.PresentationUpdateWithoutBaseInput, Prisma.PresentationUncheckedUpdateWithoutBaseInput>
}

export type PresentationUpdateWithoutBaseInput = {
  content?: Prisma.StringFieldUpdateOperationsInput | string
  imageSource?: Prisma.StringFieldUpdateOperationsInput | string
  imageProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageModelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pageStyle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  numSlides?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outline?: Prisma.PresentationUpdateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumPresentationStatusFieldUpdateOperationsInput | $Enums.PresentationStatus
  theme?: Prisma.PresentationThemeUpdateOneWithoutPresentationsNestedInput
}

export type PresentationUncheckedUpdateWithoutBaseInput = {
  content?: Prisma.StringFieldUpdateOperationsInput | string
  imageSource?: Prisma.StringFieldUpdateOperationsInput | string
  imageProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageModelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pageStyle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  numSlides?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outline?: Prisma.PresentationUpdateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPresentationStatusFieldUpdateOperationsInput | $Enums.PresentationStatus
}

export type PresentationCreateWithoutThemeInput = {
  content: string
  imageSource?: string
  imageProvider?: string | null
  imageModelId?: string | null
  prompt?: string | null
  modelProvider?: string | null
  modelId?: string | null
  pageStyle?: string | null
  numSlides?: number | null
  tone?: string | null
  language?: string | null
  outline?: Prisma.PresentationCreateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: string | null
  status?: $Enums.PresentationStatus
  base?: Prisma.BaseDocumentCreateNestedOneWithoutPresentationInput
}

export type PresentationUncheckedCreateWithoutThemeInput = {
  id?: string
  content: string
  imageSource?: string
  imageProvider?: string | null
  imageModelId?: string | null
  prompt?: string | null
  modelProvider?: string | null
  modelId?: string | null
  pageStyle?: string | null
  numSlides?: number | null
  tone?: string | null
  language?: string | null
  outline?: Prisma.PresentationCreateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: string | null
  status?: $Enums.PresentationStatus
}

export type PresentationCreateOrConnectWithoutThemeInput = {
  where: Prisma.PresentationWhereUniqueInput
  create: Prisma.XOR<Prisma.PresentationCreateWithoutThemeInput, Prisma.PresentationUncheckedCreateWithoutThemeInput>
}

export type PresentationCreateManyThemeInputEnvelope = {
  data: Prisma.PresentationCreateManyThemeInput | Prisma.PresentationCreateManyThemeInput[]
  skipDuplicates?: boolean
}

export type PresentationUpsertWithWhereUniqueWithoutThemeInput = {
  where: Prisma.PresentationWhereUniqueInput
  update: Prisma.XOR<Prisma.PresentationUpdateWithoutThemeInput, Prisma.PresentationUncheckedUpdateWithoutThemeInput>
  create: Prisma.XOR<Prisma.PresentationCreateWithoutThemeInput, Prisma.PresentationUncheckedCreateWithoutThemeInput>
}

export type PresentationUpdateWithWhereUniqueWithoutThemeInput = {
  where: Prisma.PresentationWhereUniqueInput
  data: Prisma.XOR<Prisma.PresentationUpdateWithoutThemeInput, Prisma.PresentationUncheckedUpdateWithoutThemeInput>
}

export type PresentationUpdateManyWithWhereWithoutThemeInput = {
  where: Prisma.PresentationScalarWhereInput
  data: Prisma.XOR<Prisma.PresentationUpdateManyMutationInput, Prisma.PresentationUncheckedUpdateManyWithoutThemeInput>
}

export type PresentationScalarWhereInput = {
  AND?: Prisma.PresentationScalarWhereInput | Prisma.PresentationScalarWhereInput[]
  OR?: Prisma.PresentationScalarWhereInput[]
  NOT?: Prisma.PresentationScalarWhereInput | Prisma.PresentationScalarWhereInput[]
  id?: Prisma.StringFilter<"Presentation"> | string
  content?: Prisma.StringFilter<"Presentation"> | string
  imageSource?: Prisma.StringFilter<"Presentation"> | string
  imageProvider?: Prisma.StringNullableFilter<"Presentation"> | string | null
  imageModelId?: Prisma.StringNullableFilter<"Presentation"> | string | null
  prompt?: Prisma.StringNullableFilter<"Presentation"> | string | null
  modelProvider?: Prisma.StringNullableFilter<"Presentation"> | string | null
  modelId?: Prisma.StringNullableFilter<"Presentation"> | string | null
  pageStyle?: Prisma.StringNullableFilter<"Presentation"> | string | null
  numSlides?: Prisma.IntNullableFilter<"Presentation"> | number | null
  tone?: Prisma.StringNullableFilter<"Presentation"> | string | null
  language?: Prisma.StringNullableFilter<"Presentation"> | string | null
  outline?: Prisma.StringNullableListFilter<"Presentation">
  searchResults?: Prisma.JsonNullableFilter<"Presentation">
  templateId?: Prisma.StringNullableFilter<"Presentation"> | string | null
  themeId?: Prisma.StringFilter<"Presentation"> | string
  status?: Prisma.EnumPresentationStatusFilter<"Presentation"> | $Enums.PresentationStatus
}

export type PresentationCreateManyThemeInput = {
  id?: string
  content: string
  imageSource?: string
  imageProvider?: string | null
  imageModelId?: string | null
  prompt?: string | null
  modelProvider?: string | null
  modelId?: string | null
  pageStyle?: string | null
  numSlides?: number | null
  tone?: string | null
  language?: string | null
  outline?: Prisma.PresentationCreateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: string | null
  status?: $Enums.PresentationStatus
}

export type PresentationUpdateWithoutThemeInput = {
  content?: Prisma.StringFieldUpdateOperationsInput | string
  imageSource?: Prisma.StringFieldUpdateOperationsInput | string
  imageProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageModelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pageStyle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  numSlides?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outline?: Prisma.PresentationUpdateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumPresentationStatusFieldUpdateOperationsInput | $Enums.PresentationStatus
  base?: Prisma.BaseDocumentUpdateOneRequiredWithoutPresentationNestedInput
}

export type PresentationUncheckedUpdateWithoutThemeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  imageSource?: Prisma.StringFieldUpdateOperationsInput | string
  imageProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageModelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pageStyle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  numSlides?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outline?: Prisma.PresentationUpdateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumPresentationStatusFieldUpdateOperationsInput | $Enums.PresentationStatus
}

export type PresentationUncheckedUpdateManyWithoutThemeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  imageSource?: Prisma.StringFieldUpdateOperationsInput | string
  imageProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageModelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prompt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelProvider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  modelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pageStyle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  numSlides?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outline?: Prisma.PresentationUpdateoutlineInput | string[]
  searchResults?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  templateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumPresentationStatusFieldUpdateOperationsInput | $Enums.PresentationStatus
}



export type PresentationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  content?: boolean
  imageSource?: boolean
  imageProvider?: boolean
  imageModelId?: boolean
  prompt?: boolean
  modelProvider?: boolean
  modelId?: boolean
  pageStyle?: boolean
  numSlides?: boolean
  tone?: boolean
  language?: boolean
  outline?: boolean
  searchResults?: boolean
  templateId?: boolean
  themeId?: boolean
  status?: boolean
  base?: boolean | Prisma.BaseDocumentDefaultArgs<ExtArgs>
  theme?: boolean | Prisma.Presentation$themeArgs<ExtArgs>
}, ExtArgs["result"]["presentation"]>

export type PresentationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  content?: boolean
  imageSource?: boolean
  imageProvider?: boolean
  imageModelId?: boolean
  prompt?: boolean
  modelProvider?: boolean
  modelId?: boolean
  pageStyle?: boolean
  numSlides?: boolean
  tone?: boolean
  language?: boolean
  outline?: boolean
  searchResults?: boolean
  templateId?: boolean
  themeId?: boolean
  status?: boolean
  base?: boolean | Prisma.BaseDocumentDefaultArgs<ExtArgs>
  theme?: boolean | Prisma.Presentation$themeArgs<ExtArgs>
}, ExtArgs["result"]["presentation"]>

export type PresentationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  content?: boolean
  imageSource?: boolean
  imageProvider?: boolean
  imageModelId?: boolean
  prompt?: boolean
  modelProvider?: boolean
  modelId?: boolean
  pageStyle?: boolean
  numSlides?: boolean
  tone?: boolean
  language?: boolean
  outline?: boolean
  searchResults?: boolean
  templateId?: boolean
  themeId?: boolean
  status?: boolean
  base?: boolean | Prisma.BaseDocumentDefaultArgs<ExtArgs>
  theme?: boolean | Prisma.Presentation$themeArgs<ExtArgs>
}, ExtArgs["result"]["presentation"]>

export type PresentationSelectScalar = {
  id?: boolean
  content?: boolean
  imageSource?: boolean
  imageProvider?: boolean
  imageModelId?: boolean
  prompt?: boolean
  modelProvider?: boolean
  modelId?: boolean
  pageStyle?: boolean
  numSlides?: boolean
  tone?: boolean
  language?: boolean
  outline?: boolean
  searchResults?: boolean
  templateId?: boolean
  themeId?: boolean
  status?: boolean
}

export type PresentationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "content" | "imageSource" | "imageProvider" | "imageModelId" | "prompt" | "modelProvider" | "modelId" | "pageStyle" | "numSlides" | "tone" | "language" | "outline" | "searchResults" | "templateId" | "themeId" | "status", ExtArgs["result"]["presentation"]>
export type PresentationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  base?: boolean | Prisma.BaseDocumentDefaultArgs<ExtArgs>
  theme?: boolean | Prisma.Presentation$themeArgs<ExtArgs>
}
export type PresentationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  base?: boolean | Prisma.BaseDocumentDefaultArgs<ExtArgs>
  theme?: boolean | Prisma.Presentation$themeArgs<ExtArgs>
}
export type PresentationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  base?: boolean | Prisma.BaseDocumentDefaultArgs<ExtArgs>
  theme?: boolean | Prisma.Presentation$themeArgs<ExtArgs>
}

export type $PresentationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Presentation"
  objects: {
    base: Prisma.$BaseDocumentPayload<ExtArgs>
    theme: Prisma.$PresentationThemePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    content: string
    imageSource: string
    imageProvider: string | null
    imageModelId: string | null
    prompt: string | null
    modelProvider: string | null
    modelId: string | null
    pageStyle: string | null
    numSlides: number | null
    tone: string | null
    language: string | null
    outline: string[]
    searchResults: runtime.JsonValue | null
    templateId: string | null
    themeId: string
    status: $Enums.PresentationStatus
  }, ExtArgs["result"]["presentation"]>
  composites: {}
}

export type PresentationGetPayload<S extends boolean | null | undefined | PresentationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PresentationPayload, S>

export type PresentationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PresentationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PresentationCountAggregateInputType | true
  }

export interface PresentationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Presentation'], meta: { name: 'Presentation' } }
  /**
   * Find zero or one Presentation that matches the filter.
   * @param {PresentationFindUniqueArgs} args - Arguments to find a Presentation
   * @example
   * // Get one Presentation
   * const presentation = await prisma.presentation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PresentationFindUniqueArgs>(args: Prisma.SelectSubset<T, PresentationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PresentationClient<runtime.Types.Result.GetResult<Prisma.$PresentationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Presentation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PresentationFindUniqueOrThrowArgs} args - Arguments to find a Presentation
   * @example
   * // Get one Presentation
   * const presentation = await prisma.presentation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PresentationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PresentationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PresentationClient<runtime.Types.Result.GetResult<Prisma.$PresentationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Presentation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PresentationFindFirstArgs} args - Arguments to find a Presentation
   * @example
   * // Get one Presentation
   * const presentation = await prisma.presentation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PresentationFindFirstArgs>(args?: Prisma.SelectSubset<T, PresentationFindFirstArgs<ExtArgs>>): Prisma.Prisma__PresentationClient<runtime.Types.Result.GetResult<Prisma.$PresentationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Presentation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PresentationFindFirstOrThrowArgs} args - Arguments to find a Presentation
   * @example
   * // Get one Presentation
   * const presentation = await prisma.presentation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PresentationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PresentationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PresentationClient<runtime.Types.Result.GetResult<Prisma.$PresentationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Presentations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PresentationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Presentations
   * const presentations = await prisma.presentation.findMany()
   * 
   * // Get first 10 Presentations
   * const presentations = await prisma.presentation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const presentationWithIdOnly = await prisma.presentation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PresentationFindManyArgs>(args?: Prisma.SelectSubset<T, PresentationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PresentationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Presentation.
   * @param {PresentationCreateArgs} args - Arguments to create a Presentation.
   * @example
   * // Create one Presentation
   * const Presentation = await prisma.presentation.create({
   *   data: {
   *     // ... data to create a Presentation
   *   }
   * })
   * 
   */
  create<T extends PresentationCreateArgs>(args: Prisma.SelectSubset<T, PresentationCreateArgs<ExtArgs>>): Prisma.Prisma__PresentationClient<runtime.Types.Result.GetResult<Prisma.$PresentationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Presentations.
   * @param {PresentationCreateManyArgs} args - Arguments to create many Presentations.
   * @example
   * // Create many Presentations
   * const presentation = await prisma.presentation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PresentationCreateManyArgs>(args?: Prisma.SelectSubset<T, PresentationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Presentations and returns the data saved in the database.
   * @param {PresentationCreateManyAndReturnArgs} args - Arguments to create many Presentations.
   * @example
   * // Create many Presentations
   * const presentation = await prisma.presentation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Presentations and only return the `id`
   * const presentationWithIdOnly = await prisma.presentation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PresentationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PresentationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PresentationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Presentation.
   * @param {PresentationDeleteArgs} args - Arguments to delete one Presentation.
   * @example
   * // Delete one Presentation
   * const Presentation = await prisma.presentation.delete({
   *   where: {
   *     // ... filter to delete one Presentation
   *   }
   * })
   * 
   */
  delete<T extends PresentationDeleteArgs>(args: Prisma.SelectSubset<T, PresentationDeleteArgs<ExtArgs>>): Prisma.Prisma__PresentationClient<runtime.Types.Result.GetResult<Prisma.$PresentationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Presentation.
   * @param {PresentationUpdateArgs} args - Arguments to update one Presentation.
   * @example
   * // Update one Presentation
   * const presentation = await prisma.presentation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PresentationUpdateArgs>(args: Prisma.SelectSubset<T, PresentationUpdateArgs<ExtArgs>>): Prisma.Prisma__PresentationClient<runtime.Types.Result.GetResult<Prisma.$PresentationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Presentations.
   * @param {PresentationDeleteManyArgs} args - Arguments to filter Presentations to delete.
   * @example
   * // Delete a few Presentations
   * const { count } = await prisma.presentation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PresentationDeleteManyArgs>(args?: Prisma.SelectSubset<T, PresentationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Presentations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PresentationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Presentations
   * const presentation = await prisma.presentation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PresentationUpdateManyArgs>(args: Prisma.SelectSubset<T, PresentationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Presentations and returns the data updated in the database.
   * @param {PresentationUpdateManyAndReturnArgs} args - Arguments to update many Presentations.
   * @example
   * // Update many Presentations
   * const presentation = await prisma.presentation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Presentations and only return the `id`
   * const presentationWithIdOnly = await prisma.presentation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PresentationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PresentationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PresentationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Presentation.
   * @param {PresentationUpsertArgs} args - Arguments to update or create a Presentation.
   * @example
   * // Update or create a Presentation
   * const presentation = await prisma.presentation.upsert({
   *   create: {
   *     // ... data to create a Presentation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Presentation we want to update
   *   }
   * })
   */
  upsert<T extends PresentationUpsertArgs>(args: Prisma.SelectSubset<T, PresentationUpsertArgs<ExtArgs>>): Prisma.Prisma__PresentationClient<runtime.Types.Result.GetResult<Prisma.$PresentationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Presentations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PresentationCountArgs} args - Arguments to filter Presentations to count.
   * @example
   * // Count the number of Presentations
   * const count = await prisma.presentation.count({
   *   where: {
   *     // ... the filter for the Presentations we want to count
   *   }
   * })
  **/
  count<T extends PresentationCountArgs>(
    args?: Prisma.Subset<T, PresentationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PresentationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Presentation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PresentationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PresentationAggregateArgs>(args: Prisma.Subset<T, PresentationAggregateArgs>): Prisma.PrismaPromise<GetPresentationAggregateType<T>>

  /**
   * Group by Presentation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PresentationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PresentationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PresentationGroupByArgs['orderBy'] }
      : { orderBy?: PresentationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PresentationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPresentationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Presentation model
 */
readonly fields: PresentationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Presentation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PresentationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  base<T extends Prisma.BaseDocumentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BaseDocumentDefaultArgs<ExtArgs>>): Prisma.Prisma__BaseDocumentClient<runtime.Types.Result.GetResult<Prisma.$BaseDocumentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  theme<T extends Prisma.Presentation$themeArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Presentation$themeArgs<ExtArgs>>): Prisma.Prisma__PresentationThemeClient<runtime.Types.Result.GetResult<Prisma.$PresentationThemePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Presentation model
 */
export interface PresentationFieldRefs {
  readonly id: Prisma.FieldRef<"Presentation", 'String'>
  readonly content: Prisma.FieldRef<"Presentation", 'String'>
  readonly imageSource: Prisma.FieldRef<"Presentation", 'String'>
  readonly imageProvider: Prisma.FieldRef<"Presentation", 'String'>
  readonly imageModelId: Prisma.FieldRef<"Presentation", 'String'>
  readonly prompt: Prisma.FieldRef<"Presentation", 'String'>
  readonly modelProvider: Prisma.FieldRef<"Presentation", 'String'>
  readonly modelId: Prisma.FieldRef<"Presentation", 'String'>
  readonly pageStyle: Prisma.FieldRef<"Presentation", 'String'>
  readonly numSlides: Prisma.FieldRef<"Presentation", 'Int'>
  readonly tone: Prisma.FieldRef<"Presentation", 'String'>
  readonly language: Prisma.FieldRef<"Presentation", 'String'>
  readonly outline: Prisma.FieldRef<"Presentation", 'String[]'>
  readonly searchResults: Prisma.FieldRef<"Presentation", 'Json'>
  readonly templateId: Prisma.FieldRef<"Presentation", 'String'>
  readonly themeId: Prisma.FieldRef<"Presentation", 'String'>
  readonly status: Prisma.FieldRef<"Presentation", 'PresentationStatus'>
}
    

// Custom InputTypes
/**
 * Presentation findUnique
 */
export type PresentationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Presentation
   */
  select?: Prisma.PresentationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Presentation
   */
  omit?: Prisma.PresentationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PresentationInclude<ExtArgs> | null
  /**
   * Filter, which Presentation to fetch.
   */
  where: Prisma.PresentationWhereUniqueInput
}

/**
 * Presentation findUniqueOrThrow
 */
export type PresentationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Presentation
   */
  select?: Prisma.PresentationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Presentation
   */
  omit?: Prisma.PresentationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PresentationInclude<ExtArgs> | null
  /**
   * Filter, which Presentation to fetch.
   */
  where: Prisma.PresentationWhereUniqueInput
}

/**
 * Presentation findFirst
 */
export type PresentationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Presentation
   */
  select?: Prisma.PresentationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Presentation
   */
  omit?: Prisma.PresentationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PresentationInclude<ExtArgs> | null
  /**
   * Filter, which Presentation to fetch.
   */
  where?: Prisma.PresentationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Presentations to fetch.
   */
  orderBy?: Prisma.PresentationOrderByWithRelationInput | Prisma.PresentationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Presentations.
   */
  cursor?: Prisma.PresentationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Presentations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Presentations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Presentations.
   */
  distinct?: Prisma.PresentationScalarFieldEnum | Prisma.PresentationScalarFieldEnum[]
}

/**
 * Presentation findFirstOrThrow
 */
export type PresentationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Presentation
   */
  select?: Prisma.PresentationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Presentation
   */
  omit?: Prisma.PresentationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PresentationInclude<ExtArgs> | null
  /**
   * Filter, which Presentation to fetch.
   */
  where?: Prisma.PresentationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Presentations to fetch.
   */
  orderBy?: Prisma.PresentationOrderByWithRelationInput | Prisma.PresentationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Presentations.
   */
  cursor?: Prisma.PresentationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Presentations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Presentations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Presentations.
   */
  distinct?: Prisma.PresentationScalarFieldEnum | Prisma.PresentationScalarFieldEnum[]
}

/**
 * Presentation findMany
 */
export type PresentationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Presentation
   */
  select?: Prisma.PresentationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Presentation
   */
  omit?: Prisma.PresentationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PresentationInclude<ExtArgs> | null
  /**
   * Filter, which Presentations to fetch.
   */
  where?: Prisma.PresentationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Presentations to fetch.
   */
  orderBy?: Prisma.PresentationOrderByWithRelationInput | Prisma.PresentationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Presentations.
   */
  cursor?: Prisma.PresentationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Presentations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Presentations.
   */
  skip?: number
  distinct?: Prisma.PresentationScalarFieldEnum | Prisma.PresentationScalarFieldEnum[]
}

/**
 * Presentation create
 */
export type PresentationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Presentation
   */
  select?: Prisma.PresentationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Presentation
   */
  omit?: Prisma.PresentationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PresentationInclude<ExtArgs> | null
  /**
   * The data needed to create a Presentation.
   */
  data: Prisma.XOR<Prisma.PresentationCreateInput, Prisma.PresentationUncheckedCreateInput>
}

/**
 * Presentation createMany
 */
export type PresentationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Presentations.
   */
  data: Prisma.PresentationCreateManyInput | Prisma.PresentationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Presentation createManyAndReturn
 */
export type PresentationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Presentation
   */
  select?: Prisma.PresentationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Presentation
   */
  omit?: Prisma.PresentationOmit<ExtArgs> | null
  /**
   * The data used to create many Presentations.
   */
  data: Prisma.PresentationCreateManyInput | Prisma.PresentationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PresentationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Presentation update
 */
export type PresentationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Presentation
   */
  select?: Prisma.PresentationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Presentation
   */
  omit?: Prisma.PresentationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PresentationInclude<ExtArgs> | null
  /**
   * The data needed to update a Presentation.
   */
  data: Prisma.XOR<Prisma.PresentationUpdateInput, Prisma.PresentationUncheckedUpdateInput>
  /**
   * Choose, which Presentation to update.
   */
  where: Prisma.PresentationWhereUniqueInput
}

/**
 * Presentation updateMany
 */
export type PresentationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Presentations.
   */
  data: Prisma.XOR<Prisma.PresentationUpdateManyMutationInput, Prisma.PresentationUncheckedUpdateManyInput>
  /**
   * Filter which Presentations to update
   */
  where?: Prisma.PresentationWhereInput
  /**
   * Limit how many Presentations to update.
   */
  limit?: number
}

/**
 * Presentation updateManyAndReturn
 */
export type PresentationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Presentation
   */
  select?: Prisma.PresentationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Presentation
   */
  omit?: Prisma.PresentationOmit<ExtArgs> | null
  /**
   * The data used to update Presentations.
   */
  data: Prisma.XOR<Prisma.PresentationUpdateManyMutationInput, Prisma.PresentationUncheckedUpdateManyInput>
  /**
   * Filter which Presentations to update
   */
  where?: Prisma.PresentationWhereInput
  /**
   * Limit how many Presentations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PresentationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Presentation upsert
 */
export type PresentationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Presentation
   */
  select?: Prisma.PresentationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Presentation
   */
  omit?: Prisma.PresentationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PresentationInclude<ExtArgs> | null
  /**
   * The filter to search for the Presentation to update in case it exists.
   */
  where: Prisma.PresentationWhereUniqueInput
  /**
   * In case the Presentation found by the `where` argument doesn't exist, create a new Presentation with this data.
   */
  create: Prisma.XOR<Prisma.PresentationCreateInput, Prisma.PresentationUncheckedCreateInput>
  /**
   * In case the Presentation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PresentationUpdateInput, Prisma.PresentationUncheckedUpdateInput>
}

/**
 * Presentation delete
 */
export type PresentationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Presentation
   */
  select?: Prisma.PresentationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Presentation
   */
  omit?: Prisma.PresentationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PresentationInclude<ExtArgs> | null
  /**
   * Filter which Presentation to delete.
   */
  where: Prisma.PresentationWhereUniqueInput
}

/**
 * Presentation deleteMany
 */
export type PresentationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Presentations to delete
   */
  where?: Prisma.PresentationWhereInput
  /**
   * Limit how many Presentations to delete.
   */
  limit?: number
}

/**
 * Presentation.theme
 */
export type Presentation$themeArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PresentationTheme
   */
  select?: Prisma.PresentationThemeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PresentationTheme
   */
  omit?: Prisma.PresentationThemeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PresentationThemeInclude<ExtArgs> | null
  where?: Prisma.PresentationThemeWhereInput
}

/**
 * Presentation without action
 */
export type PresentationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Presentation
   */
  select?: Prisma.PresentationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Presentation
   */
  omit?: Prisma.PresentationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PresentationInclude<ExtArgs> | null
}
